#!/usr/bin/env bash
# Regenerates tests/browser/happy-dom.mjs: happy-dom, bundled by esbuild
# into one ES module that imports nothing but Node's own modules. It is the
# DOM the `browser/` corpus kind runs programs in under Node, vendored so
# that the gates need no network and no `node_modules`, and every machine
# runs the same bytes.
#
# The only step here that needs the network. Run it by hand to move the
# pin, then update `dom_id` and `dom_sha256` in
# tests/blackbox/browser.zig with what it prints, run
# `zig build test-run-hashes` (every browser record changes) and commit the
# three together. The same versions give the same bytes, so running it
# without changing them must reproduce the checked-in file exactly.
set -euo pipefail

HAPPY_DOM=20.14.5
ESBUILD=0.28.2
# happy-dom's own dependencies, pinned too, so that npm cannot resolve a
# newer one and change the bytes.
DEPENDENCIES="buffer-image-size@0.6.4 entities@7.0.1 whatwg-mimetype@3.0.0 ws@8.22.0"

here="$(cd "$(dirname "$0")" && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

cd "$work"
npm init -y >/dev/null
npm install --no-audit --no-fund --ignore-scripts \
  "happy-dom@$HAPPY_DOM" "esbuild@$ESBUILD" $DEPENDENCIES >/dev/null
echo 'export { GlobalWindow } from "happy-dom";' >entry.mjs
# `--ignore-scripts` skips esbuild's install script, which only links the
# platform binary this calls directly.
esbuild="$(ls node_modules/@esbuild/*/bin/esbuild | head -n 1)"
# The banner gives the bundled CommonJS dependencies the `require` an ES
# module lacks.
"$esbuild" entry.mjs --bundle --format=esm --platform=node --minify \
  --legal-comments=none --log-level=warning --metafile=meta.json \
  "--banner:js=import{createRequire as __beniRequire}from'node:module';const require=__beniRequire(import.meta.url);" \
  --outfile=bundle.mjs

# Every package the bundle took code from, with its version and licence
# text, for the comment at the end of the file.
node --input-type=module -e '
import { readFileSync, readdirSync } from "node:fs";
const inputs = Object.keys(JSON.parse(readFileSync("meta.json", "utf8")).inputs);
const packages = new Set();
for (const path of inputs) {
  const m = path.match(/^node_modules\/((?:@[^/]+\/)?[^/]+)\//);
  if (m) packages.add(m[1]);
}
let out = "\n/*\n * The packages bundled above, and their licences.\n";
for (const name of [...packages].sort()) {
  const dir = `node_modules/${name}`;
  const manifest = JSON.parse(readFileSync(`${dir}/package.json`, "utf8"));
  out += ` *\n * ${name} ${manifest.version} (${manifest.license})\n`;
  const file = readdirSync(dir).find((f) => /^licen[cs]e/i.test(f));
  if (file) for (const line of readFileSync(`${dir}/${file}`, "utf8").trimEnd().split("\n")) out += ` *   ${line.replaceAll("*/", "* /")}`.trimEnd() + "\n";
}
process.stdout.write(out + " */\n");
' >licences.txt

{
  echo "// happy-dom $HAPPY_DOM (MIT, © David Ortner) and its dependencies, bundled"
  echo "// by esbuild $ESBUILD; licences at the end. Generated by"
  echo "// tests/browser/vendor.sh: do not edit."
  cat bundle.mjs licences.txt
} >"$here/happy-dom.mjs"

echo "dom_id: happy-dom-$HAPPY_DOM"
echo "dom_sha256: $(sha256sum "$here/happy-dom.mjs" | cut -d' ' -f1)"
