// Writes the static-heavy page (research 29 §11.1's E1: about 2 000
// elements, 50 text holes, one hole changed per message) in the shapes the
// in-page measurement compares:
//
//   apps/micro/beni/Inline/      one `view`, all markup in one root
//   apps/micro/beni/Helpers/     the same page split into helper functions:
//                                a section, its heading, each item and its
//                                paragraph are helpers, so every one is a block
//   apps/micro/beni/Components/  the same helpers behind one component per
//                                section, `<Card.section index value />`
//   apps/solid2/src/static.jsx   Solid 2, inline, one signal per hole
//   apps/solid2/src/helpers.jsx  Solid 2, split into components the same way
//   apps/micro/p2/static.js      P2 by hand: one template, 50 guarded writes
//
// Every page has a `#bump` button whose click sends one message that
// changes one of the 50 values, the next one each time. The generated files
// are committed; re-run `node gen-micro.mjs` after editing this file. The
// beni it writes is in `beni fmt`'s canonical form, which the gates hold it to.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SECTIONS = 50;
const ITEMS = 12;
const range = (n) => Array.from({ length: n }, (_, i) => i);
const write = (path, text) => {
  mkdirSync(dirname(join(here, path)), { recursive: true });
  writeFileSync(join(here, path), text);
};

// ---- beni ------------------------------------------------------------------

const beniModel = () => `type alias Model =
    tick : Int
${range(SECTIONS).map((k) => `    v${k} : Int`).join("\n")}


type Msg
    = Bump


update : Msg, Model → Model
update msg model =
    case msg of
        Bump →
            bump model


bump : Model → Model
bump model =
    case modBy model.tick ${SECTIONS} of
${range(SECTIONS)
  .map((k) => `        ${k === SECTIONS - 1 ? "_" : k} →\n            { model | tick = model.tick + 1, v${k} = model.v${k} + 1 }`)
  .join("\n\n")}


init : Model
init =
    { tick = 0
${range(SECTIONS).map((k) => `    , v${k} = 0`).join("\n")}
    }


main : Browser.Program
main = Tea.sandbox { init = init, update = update, view = view }
`;

const beniHeader = (what, imports = []) => `-- Generated by bench/ui/gen-micro.mjs: the static-heavy page, ${what}.
import Browser
${imports.map((i) => `import ${i}\n`).join("")}import Html exposing (Html)
import Tea


`;

const inlineSection = (k) => `        <section class="s">
            <h2>Section ${k} <span>{model.v${k}}</span></h2>
            <ul>
${range(ITEMS).map((j) => `                <li><a href="#">item ${j}</a> <em>note</em></li>`).join("\n")}
            </ul>
            <p>The static text of section ${k}, which no message changes.</p>
        </section>`;

write(
  "apps/micro/beni/Inline/Main.beni",
  `${beniHeader("written as one view")}${beniModel()}

view : Model → Html Msg
view model =
    <main>
        <button id="bump" onClick={Bump}>bump</button>
${range(SECTIONS).map(inlineSection).join("\n")}
    </main>
`,
);

const beniHelpers = (msg) => `item : String → Html ${msg}
item label = <li><a href="#">{label}</a> <em>note</em></li>


heading : Int, Int → Html ${msg}
heading index value = <h2>Section {index} <span>{value}</span></h2>


para : Int → Html ${msg}
para index = <p>The static text of section {index}, which no message changes.</p>


section : Int, Int → Html ${msg}
section index value =
    <section class="s">
        {heading index value}
        <ul>
${range(ITEMS).map((j) => `            {item "item ${j}"}`).join("\n")}
        </ul>
        {para index}
    </section>
`;

write(
  "apps/micro/beni/Helpers/Main.beni",
  `${beniHeader("split into helper functions")}${beniModel()}

${beniHelpers("Msg")}

view : Model → Html Msg
view model =
    <main>
        <button id="bump" onClick={Bump}>bump</button>
${range(SECTIONS).map((k) => `        {section ${k} model.v${k}}`).join("\n")}
    </main>
`,
);

write(
  "apps/micro/beni/Components/Card.beni",
  `-- Generated by bench/ui/gen-micro.mjs: one section of the static-heavy
-- page as a component, over the same helpers as Helpers/Main.beni.
import Html exposing (Html)


${beniHelpers("msg").replace(/section : Int, Int → Html msg\nsection index value =/, "pub section : { index : Int, value : Int } → Html msg\nsection props =").replace("{heading index value}", "{heading props.index props.value}").replace("{para index}", "{para props.index}")}`,
);

write(
  "apps/micro/beni/Components/Main.beni",
  `${beniHeader("one component per section", ["Card"])}${beniModel()}

view : Model → Html Msg
view model =
    <main>
        <button id="bump" onClick={Bump}>bump</button>
${range(SECTIONS).map((k) => `        <Card.section index={${k}} value={model.v${k}} />`).join("\n")}
    </main>
`,
);

// ---- Solid 2 -----------------------------------------------------------------

const solidPrelude = (what) => `// Generated by bench/ui/gen-micro.mjs: the static-heavy page on Solid 2, ${what}.
import { createSignal, flush } from "solid-js";
import { render } from "@solidjs/web";

const values = [${range(SECTIONS).map(() => "createSignal(0)").join(", ")}];
let tick = 0;
const bump = () => {
  const [, set] = values[tick % ${SECTIONS}];
  tick++;
  set((v) => v + 1);
};
`;

const solidMount = (app) => `
const t0 = performance.now();
render(() => ${app}, document.getElementById("main"));
flush();
window.__mount = performance.now() - t0;
window.__flush = flush;
`;

write(
  "apps/solid2/src/static.jsx",
  `${solidPrelude("inline")}
const App = () => (
  <main>
    <button id="bump" onClick={bump}>bump</button>
${range(SECTIONS)
  .map(
    (k) => `    <section class="s">
      <h2>Section ${k} <span>{values[${k}][0]()}</span></h2>
      <ul>
${range(ITEMS).map((j) => `        <li><a href="#">item ${j}</a> <em>note</em></li>`).join("\n")}
      </ul>
      <p>The static text of section ${k}, which no message changes.</p>
    </section>`,
  )
  .join("\n")}
  </main>
);
${solidMount("<App />")}`,
);

write(
  "apps/solid2/src/helpers.jsx",
  `${solidPrelude("split into components")}
const Item = (props) => (
  <li><a href="#">{props.label}</a> <em>note</em></li>
);
const Heading = (props) => (
  <h2>Section {props.index} <span>{props.value}</span></h2>
);
const Para = (props) => <p>The static text of section {props.index}, which no message changes.</p>;
const Section = (props) => (
  <section class="s">
    <Heading index={props.index} value={props.value} />
    <ul>
${range(ITEMS).map((j) => `      <Item label="item ${j}" />`).join("\n")}
    </ul>
    <Para index={props.index} />
  </section>
);

const App = () => (
  <main>
    <button id="bump" onClick={bump}>bump</button>
${range(SECTIONS).map((k) => `    <Section index={${k}} value={values[${k}][0]()} />`).join("\n")}
  </main>
);
${solidMount("<App />")}`,
);

// ---- P2 ----------------------------------------------------------------------

const p2Html = `<main><button id="bump">bump</button>${range(SECTIONS)
  .map(
    (k) =>
      `<section class="s"><h2>Section ${k} <span> </span></h2><ul>${range(ITEMS)
        .map((j) => `<li><a href="#">item ${j}</a> <em>note</em></li>`)
        .join("")}</ul><p>The static text of section ${k}, which no message changes.</p></section>`,
  )
  .join("")}</main>`;

write(
  "apps/micro/p2/static.js",
  `// Generated by bench/ui/gen-micro.mjs: the static-heavy page as research 29's
// P2 would emit it by hand — one template for the page, the 50 hole nodes
// found once at mount, and per message a new model and one guarded write per
// hole.
const t0 = performance.now();
const TPL = document.createElement("template");
TPL.innerHTML = ${JSON.stringify(p2Html)};
const root = TPL.content.firstChild.cloneNode(true);
const holes = [];
for (let s = root.firstChild.nextSibling; s !== null; s = s.nextSibling) holes.push(s.firstChild.lastChild.firstChild);
${range(SECTIONS).map((k) => `const n${k} = holes[${k}];`).join("\n")}
let model = { tick: 0, ${range(SECTIONS).map((k) => `v${k}: 0`).join(", ")} };
${range(SECTIONS).map((k) => `let h${k} = null;`).join("\n")}
const update = (m) => {
  switch (m.tick % ${SECTIONS}) {
${range(SECTIONS).map((k) => `    case ${k}: return { ...m, tick: m.tick + 1, v${k}: m.v${k} + 1 };`).join("\n")}
  }
};
const render = (m) => {
${range(SECTIONS).map((k) => `  if (m.v${k} !== h${k}) { h${k} = m.v${k}; n${k}.data = "" + m.v${k}; }`).join("\n")}
};
render(model);
document.body.appendChild(root);
root.firstChild.addEventListener("click", () => {
  model = update(model);
  render(model);
});
window.__mount = performance.now() - t0;
window.__flush = () => {};
`,
);

console.log("wrote the static-heavy pages");
