//! The `browser/` corpus kind's harness: where its driver, its DOM and its
//! test platform are, and the headless Chrome `zig build test-browser`
//! runs the same fixtures in (tests/corpus/README.md, `browser/`).
//!
//! A fixture is built like a `run/` one, for the `page` test platform
//! (`tests/platforms/page`) unless it carries a `platform/` of its own, and
//! then `tests/browser/driver.mjs` loads the build into a page, runs the
//! fixture's `.steps` against it and prints what the page showed after each
//! step; that transcript is the golden. The gates run the page in Node under
//! happy-dom, vendored as one file (`tests/browser/vendor.sh`), so they need
//! neither a browser nor the network; `test-browser` runs it in Chrome.
//!
//! **Why happy-dom, and not linkedom, jsdom or Chrome, in the gates.**
//! Measured on a Ryzen 9 5950X with Node 24.19, a fixture-sized page
//! (mount, three clicks, serialise) in a fresh process, CPU per page: bare
//! Node 30 ms; linkedom 0.18 bundled into one file 56 (151 from
//! `node_modules`); happy-dom 20.14 bundled 115 (336 from `node_modules`);
//! jsdom 30.1, from `node_modules`, 705. One headless Chrome 153 with a
//! fresh target per page: 32 ms of wall time a page one at a time, 20 at 8
//! in flight, 36 ms of CPU, after 0.7 s of CPU to start. Across the harness
//! itself, 24 fixtures (48 builds and pages) on 8 workers took 1.2 s of wall
//! time and 8.9 s of CPU under happy-dom, 2.3 s and 11.1 s in Chromium
//! 153. Chrome is not in the flake's default shell
//! (Chromium is 454 MiB, and Linux only), a skip without it would leave the
//! gates unproven on most machines, and a browser shared by every case has
//! no place in a per-case instruction budget. Against Chrome, on eight
//! probes — `<!>` in a template, a `<table>` without `<tbody>`,
//! `<p><div>`, `<template>`'s content, an input's `value` against its
//! attribute, a checkbox's activation, focus, and an exception in a
//! listener — happy-dom differed on one (the empty `<p></p>` the parser
//! makes after a misnested `</p>`) and linkedom on seven, including
//! dropping everything after a `<!>`, the marker the `dom` lowering's
//! templates are made of. So the gates pay about 60 ms of CPU more per
//! page than linkedom would cost for a DOM that behaves like the browser,
//! and the run hashes below keep them from paying it for a page already
//! verified. A browser case, two builds and two pages, retires about 1 600
//! million instructions of the 4 300 budget.
//!
//! **Run hashes.** A browser build's record line is
//! `<pass> <node version> <dom> <sha-256>` (`run_hash.lineWith`): the
//! digest covers what a `run/` one does — the output tree, the golden, the
//! Node version — plus the DOM's name and checksum, the driver's bytes and
//! the steps, so a change to any of them runs the page again.

const std = @import("std");
const world = @import("world.zig");
const run_hash = @import("run_hash.zig");
const World = world.World;
const Io = std.Io;
const Allocator = std.mem.Allocator;
const Sha256 = std.crypto.hash.sha2.Sha256;

/// The driver, relative to the repository root.
pub const driver_path = "tests/browser/driver.mjs";

/// The vendored DOM, its name and version, and the SHA-256 of its bytes,
/// which `tests/browser/vendor.sh` prints when it writes the file.
pub const dom_path = "tests/browser/happy-dom.mjs";
pub const dom_id = "happy-dom-20.14.5";
pub const dom_sha256 = "7e09361e2353bc4bb2766b7b39754466aa37b40157c31c94cf4422bbb7aa616d";

/// The platform a fixture without a `platform/` directory is built for.
pub const platform_path = "tests/platforms/page";

/// The harness's files, resolved once per process from the working
/// directory, which is the repository root in every run the build makes.
pub const Harness = struct {
    /// Absolute paths, for a driver and a compiler that run in a test's
    /// project directory.
    driver: []const u8,
    dom: []const u8,
    platform: []const u8,
    driver_bytes: []const u8,
};

var harness_mutex: Io.Mutex = .init;
var harness_value: ?Harness = null;

/// The harness, after checking that the vendored DOM is the file its
/// checksum names: an edited or truncated DOM would otherwise be a silent
/// change to what every browser fixture ran in.
pub fn harness(io: Io) !Harness {
    harness_mutex.lockUncancelable(io);
    defer harness_mutex.unlock(io);
    if (harness_value) |h| return h;
    const gpa = std.heap.page_allocator;
    const dom_bytes = try Io.Dir.cwd().readFileAlloc(io, dom_path, gpa, .limited(world.max_stream_bytes));
    defer gpa.free(dom_bytes);
    var digest: [Sha256.digest_length]u8 = undefined;
    Sha256.hash(dom_bytes, &digest, .{});
    const hex = std.fmt.bytesToHex(digest, .lower);
    if (!std.mem.eql(u8, &hex, dom_sha256)) {
        std.debug.print(
            "{s} has SHA-256 {s}, not the {s} of {s}: it is generated by tests/browser/vendor.sh and never edited by hand\n",
            .{ dom_path, &hex, dom_sha256, dom_id },
        );
        return error.DomChecksumMismatch;
    }
    harness_value = .{
        .driver = try Io.Dir.cwd().realPathFileAlloc(io, driver_path, gpa),
        .dom = try Io.Dir.cwd().realPathFileAlloc(io, dom_path, gpa),
        .platform = try Io.Dir.cwd().realPathFileAlloc(io, platform_path, gpa),
        .driver_bytes = try Io.Dir.cwd().readFileAlloc(io, driver_path, gpa, .limited(world.max_stream_bytes)),
    };
    return harness_value.?;
}

/// What a browser build's record line covers besides the output tree and
/// the golden (`run_hash.lineWith`).
pub fn page(arena: Allocator, h: Harness, steps: []const u8) !run_hash.Page {
    return .{ .dom = dom_id, .inputs = try arena.dupe(run_hash.Page.Input, &.{
        .{ .name = "dom sha-256", .bytes = dom_sha256 },
        .{ .name = "driver", .bytes = h.driver_bytes },
        .{ .name = "steps", .bytes = steps },
    }) };
}

/// `node <driver> --dom=<dom> <entry> [<steps>]` in `w`'s project, or with
/// `--chrome=<endpoint>` for a page in the Chrome at that endpoint.
pub fn drive(
    w: *World,
    h: Harness,
    chrome: ?[]const u8,
    entry: []const u8,
    steps: ?[]const u8,
    timeout_ms: i64,
) !world.Result {
    const arena = w.arena.allocator();
    const node = w.node_exe orelse return error.NodeNotOnPath;
    var argv: std.ArrayList([]const u8) = .empty;
    try argv.appendSlice(arena, &.{ node, h.driver });
    try argv.append(arena, if (chrome) |endpoint|
        try std.fmt.allocPrint(arena, "--chrome={s}", .{endpoint})
    else
        try std.fmt.allocPrint(arena, "--dom={s}", .{h.dom}));
    try argv.append(arena, entry);
    if (steps) |s| try argv.append(arena, s);
    return world.spawnAndCapture(arena, w.gpa, w.io, argv.items, .{ .dir = w.tmp.dir }, timeout_ms);
}

/// The Chrome `test-browser` runs pages in: `BENI_CHROME` when it is set
/// and not empty, else the first of `chromium`, `google-chrome-stable` and
/// `google-chrome` on `PATH` (`nix develop .#browser` puts Chromium there).
pub fn findChrome(arena: Allocator, io: Io) ?[]const u8 {
    const given = std.testing.environ.getAlloc(arena, "BENI_CHROME") catch "";
    if (given.len != 0) return given;
    const path = std.testing.environ.getAlloc(arena, "PATH") catch return null;
    for ([_][]const u8{ "chromium", "google-chrome-stable", "google-chrome" }) |name| {
        var it = std.mem.splitScalar(u8, path, ':');
        while (it.next()) |dir| {
            if (dir.len == 0) continue;
            const candidate = std.fmt.allocPrint(arena, "{s}/{s}", .{ dir, name }) catch return null;
            Io.Dir.cwd().access(io, candidate, .{}) catch continue;
            return candidate;
        }
    }
    return null;
}

/// One headless Chrome for a whole `test-browser` walk; every page is a
/// fresh target in it (research 26 §9: one browser per run is fifteen
/// times cheaper than one per fixture). Its profile is a directory of its
/// own, and it listens on a port it picks, on the loopback interface only.
pub const Chrome = struct {
    child: std.process.Child,
    profile: World,
    /// `ws://127.0.0.1:<port>/devtools/browser/<id>`.
    endpoint: []const u8,

    /// How long Chrome may take to start listening.
    const start_timeout_ms = 30_000;

    pub fn launch(gpa: Allocator, io: Io, exe: []const u8) !Chrome {
        var profile = try World.init(gpa, io);
        errdefer profile.deinit();
        const arena = profile.arena.allocator();
        const dir = try profile.projectPath();
        const log = try profile.tmp.dir.createFile(io, "chrome.log", .{});
        defer log.close(io);
        var child = std.process.spawn(io, .{
            .argv = &.{
                exe,
                "--headless=new",
                "--remote-debugging-port=0",
                try std.fmt.allocPrint(arena, "--user-data-dir={s}/profile", .{dir}),
                "--no-first-run",
                "--no-default-browser-check",
                "--disable-gpu",
                // A page loads the program's modules from the file system.
                "--allow-file-access-from-files",
                "--disable-extensions",
                "--disable-background-networking",
                "--disable-component-update",
                "--disable-sync",
                "--mute-audio",
                // A target nobody looks at still runs its timers at speed.
                "--disable-background-timer-throttling",
                "--disable-renderer-backgrounding",
                "--disable-backgrounding-occluded-windows",
                "about:blank",
            },
            .stdin = .ignore,
            .stdout = .ignore,
            .stderr = .{ .file = log },
        }) catch |err| {
            std.debug.print("cannot start Chrome at {s}: {t}\n", .{ exe, err });
            return err;
        };
        errdefer child.kill(io);
        const deadline = Io.Timestamp.now(io, .awake).addDuration(.fromMilliseconds(start_timeout_ms));
        while (true) {
            // Chrome writes the port and the browser target's path here once
            // it listens.
            if (profile.read("profile/DevToolsActivePort")) |text| {
                var lines = std.mem.splitScalar(u8, text, '\n');
                const port = lines.next() orelse "";
                const target = lines.next() orelse "";
                if (port.len != 0 and std.mem.startsWith(u8, target, "/devtools/browser/")) {
                    return .{
                        .child = child,
                        .profile = profile,
                        .endpoint = try std.fmt.allocPrint(arena, "ws://127.0.0.1:{s}{s}", .{ port, target }),
                    };
                }
            } else |_| {}
            if (Io.Timestamp.now(io, .awake).durationTo(deadline).toMilliseconds() <= 0) {
                std.debug.print("{s} did not start listening within {d} ms; its log:\n{s}\n", .{
                    exe, start_timeout_ms, profile.read("chrome.log") catch "",
                });
                return error.ChromeDidNotStart;
            }
            try io.sleep(.fromMilliseconds(20), .awake);
        }
    }

    /// Stop Chrome and remove its profile.
    pub fn deinit(chrome: *Chrome, io: Io) void {
        chrome.child.kill(io);
        chrome.profile.deinit();
    }
};
