//! A platform compiled into beni from outside its source tree
//! (docs/design/boundary.md §9.5). `build.zig` builds a beni with
//! `tests/platforms/toy` compiled in, exactly as `zig build
//! -Dplatform=tests/platforms/toy` does, and runs this file against that
//! binary: `--platform=toy` finds the platform by name as it finds one that
//! ships, its `toy` markup lowering — Zig written against interface 1.0 and
//! importing `html`'s Zig module — is in the binary's registry, and a program
//! built for it prints what that lowering made of its view.
//!
//! Boundary 2: the emitted program under Node. Nothing here imports a
//! compiler internal.

const std = @import("std");
const world = @import("world.zig");
const World = world.World;
const testing = std.testing;

test "an external platform's markup lowering compiles a view the program then prints" {
    // ┌─────────────────────────────────────────┐
    // │ PREPARE                                 │
    // └─────────────────────────────────────────┘
    // The toy lowering writes an element as its tag and its content in
    // brackets through a function its `module` hoisted, a void element as
    // `br/` (from `html`'s parser table), quotes a text hole through its
    // runtime, and names every element's tag as program start data, which
    // the entry file hands the runtime's `start` — sorted and without
    // repeats — before `run`. Its runtime is the program runtime too, so
    // the one file is checked against the union with `run`.
    var w = try World.init(testing.allocator, testing.io);
    defer w.deinit();
    try w.write("Main.beni",
        \\import Html exposing (Html)
        \\import Toy
        \\
        \\
        \\view : String -> Html msg
        \\view name =
        \\    <p>Hi {name}<br /><b>{Html.text "!"}</b><b>?</b></p>
        \\
        \\
        \\main : Toy.Program
        \\main =
        \\    Toy.show (view "you")
        \\
    );

    // ┌─────────────────────────────────────────┐
    // │ EXECUTE                                 │
    // └─────────────────────────────────────────┘
    const built = try w.runWith(&.{ "build", "--platform=toy", "--out=out", "Main.beni" }, .{ .raw_diagnostics = true });

    // ┌─────────────────────────────────────────┐
    // │ VERIFY OUTPUT                           │
    // └─────────────────────────────────────────┘
    try testing.expectEqual(@as(u8, 0), built.exit_code);
    try testing.expectEqualStrings("", built.stderr);
    try w.expectProgram("out/_main.mjs", .{ .stdout = "p[\"Hi \" \"you\" br/[] b[\"!\"] b[\"?\"]]\ntags: b br p\n" });

    // ┌─────────────────────────────────────────┐
    // │ VERIFY SIDE EFFECTS                     │
    // └─────────────────────────────────────────┘
    // One runtime file, copied once: it is the program runtime and the
    // markup runtime both.
    const entry = try w.read("out/_main.mjs");
    try testing.expectEqualStrings(
        \\// Generated by `beni build` (docs/design/boundary.md §5.2): the entry file
        \\// the platform's output shape asks for.
        \\import { run } from "./_platform/runtime.foreign.mjs";
        \\import { start } from "./_platform/runtime.foreign.mjs";
        \\import { Main$main } from "./Main.mjs";
        \\
        \\start({"tag": ["b", "br", "p"]});
        \\run(Main$main);
        \\
    , entry);
}

test "a release application calls the runtime's start and run inside its one file" {
    // ┌─────────────────────────────────────────┐
    // │ PREPARE                                 │
    // └─────────────────────────────────────────┘
    // The toy runtime is the program runtime and the markup runtime both.
    // Under `--release` an application is one scope-hoisted file
    // (`backend.md` §9, *One scope-hoisted file under `--release`*): the
    // runtime, the toy sibling and `Main`, in the order the entry file would
    // have evaluated them, then the entry's `start` and `run` calls by the
    // names those bindings have in the one scope. The development build keeps
    // its two `import` lines, pinned above.
    var w = try World.init(testing.allocator, testing.io);
    defer w.deinit();
    try w.write("Main.beni",
        \\import Html exposing (Html)
        \\import Toy
        \\
        \\
        \\view : String -> Html msg
        \\view name =
        \\    <p>Hi {name}</p>
        \\
        \\
        \\main : Toy.Program
        \\main =
        \\    Toy.show (view "you")
        \\
    );

    // ┌─────────────────────────────────────────┐
    // │ EXECUTE                                 │
    // └─────────────────────────────────────────┘
    const built = try w.runWith(&.{ "build", "--platform=toy", "--release", "--out=out", "Main.beni" }, .{ .raw_diagnostics = true });

    // ┌─────────────────────────────────────────┐
    // │ VERIFY OUTPUT                           │
    // └─────────────────────────────────────────┘
    try testing.expectEqual(@as(u8, 0), built.exit_code);
    try testing.expectEqualStrings("", built.stderr);
    try w.expectProgram("out/_main.mjs", .{ .stdout = "p[\"Hi \" \"you\"]\ntags: p\n" });

    // ┌─────────────────────────────────────────┐
    // │ VERIFY SIDE EFFECTS                     │
    // └─────────────────────────────────────────┘
    try testing.expectEqualStrings(
        \\import process from"node:process";
        \\let g=[];let h=a=>{g=a.tag};let i=c=>{process.stdout.write(`${c.html.t}\ntags: ${g.join(" ")}\n`)};let b=d=>`"${d}"`;
        \\let a=html=>({html});
        \\function c(a,b){return a+"["+b+"]";}
        \\const d=(a)=>({t:c("p","\"Hi \""+" "+b(a))}),
        \\e=a(d("you"));
        \\h({"tag":["p"]});
        \\i(e);
        \\
    , try w.read("out/_main.mjs"));
}
