//! `zig build test-time-report`'s tool, end to end on one corpus fixture:
//! the report tool runs the corpus walker with timing on, the walker writes
//! its records, and the report comes out whole.
//!
//! The walker runs directly, one part of it, rather than under a child
//! `zig build`: the build runner's own work cost more CPU than the walker,
//! the tool and this test together, and what is under test is the tool and
//! the records. `BENI_TIME_REPORT_EXE` and `BENI_CORPUS_TEST_EXE` come from
//! `build.zig`.

const std = @import("std");
const testing = std.testing;
const world = @import("world.zig");
const World = world.World;

/// The one fixture the walker runs: a small `parse/good` file, one
/// `dump` of it.
const fixture = "tests/corpus/parse/good/BlankLines.beni";

test "the time report of one corpus fixture has every table and names the fixture" {
    // ┌─────────────────────────────────────────┐
    // │ PREPARE                                 │
    // └─────────────────────────────────────────┘
    const gpa = testing.allocator;
    var w = try World.init(gpa, testing.io);
    defer w.deinit();
    const arena = w.arena.allocator();
    const project = try w.projectPath();
    const records = try std.fs.path.join(arena, &.{ project, "records" });
    const report = try std.fs.path.join(arena, &.{ project, "report.md" });

    var argv: std.ArrayList([]const u8) = .empty;
    try argv.appendSlice(arena, &.{
        try testing.environ.getAlloc(arena, "BENI_TIME_REPORT_EXE"),
        "run",
        try std.fmt.allocPrint(arena, "--records={s}", .{records}),
        try std.fmt.allocPrint(arena, "--out={s}", .{report}),
        "--top=5",
        "--",
        try testing.environ.getAlloc(arena, "BENI_CORPUS_TEST_EXE"),
    });
    // The walker's knobs as `build.zig` pinned them for this test, then the
    // one part and the one fixture.
    var env = try testing.environ.createMap(arena);
    try env.put("BENI_CORPUS_PART", "parse");
    try env.put("BENI_CORPUS_ONLY", fixture);
    // The walker's own CPU budget is not what this test is about.
    _ = env.swapRemove("BENI_TEST_BUDGET_MS");

    // ┌─────────────────────────────────────────┐
    // │ EXECUTE                                 │
    // └─────────────────────────────────────────┘
    const r = try world.spawnAndCaptureIn(arena, testing.io, argv.items, .inherit, world.default_timeout_ms, &env);

    // ┌─────────────────────────────────────────┐
    // │ VERIFY OUTPUT                           │
    // └─────────────────────────────────────────┘
    if (r.exit_code != 0) std.debug.print("--- stdout ---\n{s}\n--- stderr ---\n{s}\n", .{ r.stdout, r.stderr });
    try testing.expectEqual(0, r.exit_code);
    const text = try w.read("report.md");
    // A file without markers gets the block, marked.
    try testing.expect(std.mem.startsWith(u8, text, "<!-- test-time-report:begin -->\n<!-- Generated by `zig build test-time-report`"));
    try testing.expect(std.mem.endsWith(u8, text, "<!-- test-time-report:end -->\n"));

    var headings: std.ArrayList([]const u8) = .empty;
    var steps: std.ArrayList([]const u8) = .empty;
    var fixture_rows: std.ArrayList([]const u8) = .empty;
    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |line| {
        if (std.mem.startsWith(u8, line, "### ")) try headings.append(arena, line);
        if (std.mem.startsWith(u8, line, "| corpus_test part ")) try steps.append(arena, cell(line, 0));
        if (std.mem.startsWith(u8, line, "| 1 | " ++ fixture ++ " |")) try fixture_rows.append(arena, line);
    }
    try testing.expectEqualDeep(@as([]const []const u8, &.{
        "### The run",
        "### Per step",
        "### Per test",
        "### Per fixture",
        "### Per tool",
        "### Harness overhead against children",
        "### Repeated invocations",
    }), headings.items);
    // The walker's process recorded itself under its part.
    try testing.expectEqualDeep(@as([]const []const u8, &.{"corpus_test part parse"}), steps.items);
    // The one case: its kind and its one `dump`; the CPU figures vary.
    try testing.expectEqual(1, fixture_rows.items.len);
    try testing.expectEqualStrings("parse_good", cell(fixture_rows.items[0], 2));
    try testing.expect(std.mem.startsWith(u8, cell(fixture_rows.items[0], 6), "1 / "));
    try testing.expect(std.mem.startsWith(u8, cell(fixture_rows.items[0], 7), "0 / "));

    // ┌─────────────────────────────────────────┐
    // │ VERIFY SIDE EFFECTS                     │
    // └─────────────────────────────────────────┘
    // The walker's record file, and the run's own measurements.
    const files = try w.listFiles("records");
    try testing.expectEqual(2, files.len);
    try testing.expect(std.mem.startsWith(u8, files[0], "corpus_test-"));
    try testing.expect(std.mem.endsWith(u8, files[0], ".jsonl"));
    try testing.expectEqualStrings("run.json", files[1]);
}

/// The text of the `index`-th cell of a Markdown table row, trimmed.
fn cell(row: []const u8, index: usize) []const u8 {
    var cells = std.mem.splitScalar(u8, row, '|');
    _ = cells.next(); // before the first bar
    var i: usize = 0;
    while (cells.next()) |c| : (i += 1) {
        if (i == index) return std.mem.trim(u8, c, " ");
    }
    return "";
}
