//! `zig build test-time-report`, end to end on one corpus fixture: the
//! report tool runs a child `zig build test-blackbox-corpus` with timing on,
//! every corpus process writes its records, and the report comes out whole.
//!
//! The child build reuses what the enclosing build already compiled (the
//! build graph makes this test wait for the corpus binary and the report
//! tool), so the run costs seconds: one fixture, five walker processes.
//! `BENI_TIME_REPORT_EXE`, `BENI_ZIG_EXE` and `BENI_CHILD_BUILD_ARGS` come
//! from `build.zig`.

const std = @import("std");
const testing = std.testing;
const world = @import("world.zig");
const World = world.World;

/// The one fixture the child build runs: a small `parse/good` file, one
/// `dump` of it.
const fixture = "tests/corpus/parse/good/BlankLines.beni";

test "the time report of one corpus fixture has every table and names the fixture" {
    // ┌─────────────────────────────────────────┐
    // │ PREPARE                                 │
    // └─────────────────────────────────────────┘
    const gpa = testing.allocator;
    var w = try World.init(gpa, testing.io);
    defer w.deinit();
    const arena = w.arena.allocator();
    const project = try w.projectPath();
    const records = try std.fs.path.join(arena, &.{ project, "records" });
    const report = try std.fs.path.join(arena, &.{ project, "report.md" });

    var argv: std.ArrayList([]const u8) = .empty;
    try argv.appendSlice(arena, &.{
        try testing.environ.getAlloc(arena, "BENI_TIME_REPORT_EXE"),
        "run",
        try std.fmt.allocPrint(arena, "--records={s}", .{records}),
        try std.fmt.allocPrint(arena, "--out={s}", .{report}),
        "--top=5",
        "--",
        try testing.environ.getAlloc(arena, "BENI_ZIG_EXE"),
        "build",
        "test-blackbox-corpus",
        "-Dcorpus=" ++ fixture,
    });
    var extra = std.mem.tokenizeScalar(u8, try testing.environ.getAlloc(arena, "BENI_CHILD_BUILD_ARGS"), ' ');
    while (extra.next()) |arg| try argv.append(arena, arg);
    // The child build needs the dev shell's `PATH` and Zig cache variables.
    var env = try testing.environ.createMap(arena);

    // ┌─────────────────────────────────────────┐
    // │ EXECUTE                                 │
    // └─────────────────────────────────────────┘
    const r = try world.spawnAndCaptureIn(arena, testing.io, argv.items, .inherit, world.default_timeout_ms, &env);

    // ┌─────────────────────────────────────────┐
    // │ VERIFY OUTPUT                           │
    // └─────────────────────────────────────────┘
    if (r.exit_code != 0) std.debug.print("--- stdout ---\n{s}\n--- stderr ---\n{s}\n", .{ r.stdout, r.stderr });
    try testing.expectEqual(0, r.exit_code);
    const text = try w.read("report.md");
    // A file without markers gets the block, marked.
    try testing.expect(std.mem.startsWith(u8, text, "<!-- test-time-report:begin -->\n<!-- Generated by `zig build test-time-report`"));
    try testing.expect(std.mem.endsWith(u8, text, "<!-- test-time-report:end -->\n"));

    var headings: std.ArrayList([]const u8) = .empty;
    var steps: std.ArrayList([]const u8) = .empty;
    var fixture_rows: std.ArrayList([]const u8) = .empty;
    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |line| {
        if (std.mem.startsWith(u8, line, "### ")) try headings.append(arena, line);
        if (std.mem.startsWith(u8, line, "| corpus_test part ")) try steps.append(arena, cell(line, 0));
        if (std.mem.startsWith(u8, line, "| 1 | " ++ fixture ++ " |")) try fixture_rows.append(arena, line);
    }
    try testing.expectEqualDeep(@as([]const []const u8, &.{
        "### The run",
        "### Per step",
        "### Per test",
        "### Per fixture",
        "### Per tool",
        "### Harness overhead against children",
        "### Repeated invocations",
    }), headings.items);
    // Every part of the walker ran and recorded itself, even the four the
    // filter left with nothing to do.
    std.mem.sort([]const u8, steps.items, {}, lessThan);
    try testing.expectEqualDeep(@as([]const []const u8, &.{
        "corpus_test part build",
        "corpus_test part check",
        "corpus_test part parse",
        "corpus_test part run_dev",
        "corpus_test part run_release",
    }), steps.items);
    // The one case: its kind and its one `dump`; the CPU figures vary.
    try testing.expectEqual(1, fixture_rows.items.len);
    try testing.expectEqualStrings("parse_good", cell(fixture_rows.items[0], 2));
    try testing.expect(std.mem.startsWith(u8, cell(fixture_rows.items[0], 6), "1 / "));
    try testing.expect(std.mem.startsWith(u8, cell(fixture_rows.items[0], 7), "0 / "));

    // ┌─────────────────────────────────────────┐
    // │ VERIFY SIDE EFFECTS                     │
    // └─────────────────────────────────────────┘
    // One record file per walker process, and the run's own measurements.
    const files = try w.listFiles("records");
    try testing.expectEqual(6, files.len);
    for (files[0..5]) |name| {
        try testing.expect(std.mem.startsWith(u8, name, "corpus_test-"));
        try testing.expect(std.mem.endsWith(u8, name, ".jsonl"));
    }
    try testing.expectEqualStrings("run.json", files[5]);
}

/// The text of the `index`-th cell of a Markdown table row, trimmed.
fn cell(row: []const u8, index: usize) []const u8 {
    var cells = std.mem.splitScalar(u8, row, '|');
    _ = cells.next(); // before the first bar
    var i: usize = 0;
    while (cells.next()) |c| : (i += 1) {
        if (i == index) return std.mem.trim(u8, c, " ");
    }
    return "";
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}
