//! Source maps for a development build (docs/design/backend.md §11): one
//! Source Map v3 file (ECMA-426) per emitted module, `Main.mjs.map` beside
//! `Main.mjs`.
//!
//! **Recorded in the print pass, encoded after it.** The printer appends a
//! `Mapping` — the generated BYTE offset it is about to write at and the
//! node's source byte offset — at every statement and every expression whose
//! `JsIr` node carries a position (`Print.Printer.mark`); no second walk of
//! the tree. `write` then turns the byte offsets into the format's
//! line/column pairs in ONE forward scan of the printed bytes, since the
//! marks arrive in generated order, and a binary search of the module's line
//! table per mark for the source side. Both columns are in UTF-16 code
//! units, which is what the format counts (ECMA-426 §4) and what a browser
//! means by a column; ASCII, which is nearly every byte either side, costs
//! one compare per byte.
//!
//! The map holds the module's `.beni` text in `sourcesContent`, so a browser
//! shows the source without fetching it — `beni serve` serves `--out` and
//! nothing above it — and `names` holds a declaration's beni name where the
//! printed one is `Module$base`.

const std = @import("std");
const builtin = @import("builtin");
const Allocator = std.mem.Allocator;
const InternPool = @import("../InternPool.zig");

/// One recorded position: where the printer was in its output, and where
/// the node it was about to print came from.
pub const Mapping = struct {
    /// Byte offset into the printed module.
    generated: u32,
    /// Byte offset into the module's `.beni` source.
    source: u32,
    /// The beni name a binding written here had: an index into
    /// `Marks.names`, or `no_name`.
    name: u32 = no_name,

    pub const no_name = std.math.maxInt(u32);
};

/// What the printer appends to. In the printer's scratch arena.
pub const Marks = struct {
    list: std.ArrayList(Mapping) = .empty,
    /// The map's `names`, in first-use order. The printer numbers them by
    /// its own name column, so two locals both written `x` are two entries.
    names: std.ArrayList(InternPool.Symbol) = .empty,
    allocator: Allocator,

    pub fn init(allocator: Allocator) Marks {
        return .{ .allocator = allocator };
    }

    /// Record `source` at `generated`. Nested nodes often start at the same
    /// byte — a call and its callee, a binary and its left operand — and
    /// the innermost, recorded last, is kept: the format allows one segment
    /// per generated column, and the innermost is the token the reader sees
    /// first there (`a * b` starts at `a`, not at the `*` the binary is
    /// positioned on).
    pub fn add(m: *Marks, generated: usize, source: u32, name: u32) Allocator.Error!void {
        const at: u32 = @intCast(generated);
        if (m.list.items.len != 0) {
            const last = &m.list.items[m.list.items.len - 1];
            std.debug.assert(last.generated <= at);
            if (last.generated == at) {
                last.* = .{ .generated = at, .source = source, .name = if (name == Mapping.no_name) last.name else name };
                return;
            }
        }
        try m.list.append(m.allocator, .{ .generated = at, .source = source, .name = name });
    }
};

/// How a `Mapping.name` becomes text: `Print.Names`, without the import.
pub const NameText = struct {
    context: *const anyopaque,
    lookup: *const fn (context: *const anyopaque, symbol: InternPool.Symbol) []const u8,
};

pub const Input = struct {
    /// The generated file's name, as the map's `file` (`Main.mjs`).
    file: []const u8,
    /// The source's URL relative to the map (`../src/Main.beni`).
    source_url: []const u8,
    /// The module's `.beni` text, for `sourcesContent`.
    source: []const u8,
    /// The source's line table: `line_starts[l]` is the byte offset of
    /// 0-based line `l`.
    line_starts: []const u32,
    /// The printed module.
    generated: []const u8,
    /// In generated order.
    mappings: []const Mapping,
    /// `Marks.names`, and how a name becomes text.
    names: []const InternPool.Symbol,
    name_text: NameText,
};

/// The map's bytes, a JSON object and a newline, from `gpa`. Everything
/// else comes from `scratch`.
pub fn write(gpa: Allocator, scratch: Allocator, in: Input) Allocator.Error![]u8 {
    var out: std.ArrayList(u8) = .empty;
    try out.ensureTotalCapacity(scratch, 128 + in.source.len + in.mappings.len * 6);
    try out.appendSlice(scratch, "{\"version\":3,\"file\":");
    try jsonString(scratch, &out, in.file);
    try out.appendSlice(scratch, ",\"sources\":[");
    try jsonString(scratch, &out, in.source_url);
    try out.appendSlice(scratch, "],\"sourcesContent\":[");
    try jsonString(scratch, &out, in.source);
    try out.appendSlice(scratch, "],\"names\":[");

    for (in.names, 0..) |symbol, i| {
        if (i != 0) try out.append(scratch, ',');
        try jsonString(scratch, &out, in.name_text.lookup(in.name_text.context, symbol));
    }
    try out.appendSlice(scratch, "],\"mappings\":\"");
    try encodeMappings(scratch, &out, in);
    try out.appendSlice(scratch, "\"}\n");
    return gpa.dupe(u8, out.items);
}

/// The `mappings` string: `;` between generated lines, `,` between
/// segments, each segment the VLQ deltas of generated column, source index
/// (always 0: one source per map), source line, source column and, when
/// there is one, name index.
fn encodeMappings(
    scratch: Allocator,
    out: *std.ArrayList(u8),
    in: Input,
) Allocator.Error!void {
    // The generated cursor: byte offset and UTF-16 column.
    var at: usize = 0;
    var column: u32 = 0;
    // What the previous segment wrote, for the deltas. The column resets per
    // generated line; the rest run across the whole file.
    var prev_column: i64 = 0;
    var prev_source_line: i64 = 0;
    var prev_source_column: i64 = 0;
    var prev_name: i64 = 0;
    var lines: SourceLines = try .init(scratch, in.source, in.line_starts);
    var segment_on_line = false;
    for (in.mappings) |m| {
        const target = @min(@as(usize, m.generated), in.generated.len);
        while (at < target) {
            // Sixteen bytes at a time while they are plain ASCII on one line,
            // which is nearly all of a printed module.
            if (use_blocks and target - at >= block) {
                const v: Block = in.generated[at..][0..block].*;
                const special = (v >= @as(Block, @splat(0x80))) | (v == @as(Block, @splat('\n'))) | (v == @as(Block, @splat('\r')));
                if (!@reduce(.Or, special)) {
                    at += block;
                    column += block;
                    continue;
                }
            }
            const c = in.generated[at];
            if (c < 0x80) {
                at += 1;
                if (c == '\n' or (c == '\r' and (at >= in.generated.len or in.generated[at] != '\n'))) {
                    try out.append(scratch, ';');
                    column = 0;
                    prev_column = 0;
                    segment_on_line = false;
                } else column += 1;
                continue;
            }
            // U+2028 and U+2029 end a line in JavaScript.
            if (c == 0xE2 and at + 2 < in.generated.len and in.generated[at + 1] == 0x80 and
                (in.generated[at + 2] == 0xA8 or in.generated[at + 2] == 0xA9))
            {
                at += 3;
                try out.append(scratch, ';');
                column = 0;
                prev_column = 0;
                segment_on_line = false;
                continue;
            }
            column += utf16Units(c);
            at += 1;
        }
        const s = lines.position(m.source);
        if (segment_on_line and s.line == prev_source_line and s.column == prev_source_column and m.name == Mapping.no_name) continue;
        // One capacity check per segment: a comma and five fields.
        try out.ensureUnusedCapacity(scratch, 1 + 5 * max_vlq_digits);
        if (segment_on_line) out.appendAssumeCapacity(',');
        vlqAssumeCapacity(out, @as(i64, column) - prev_column);
        prev_column = column;
        vlqAssumeCapacity(out, 0);
        vlqAssumeCapacity(out, s.line - prev_source_line);
        prev_source_line = s.line;
        vlqAssumeCapacity(out, s.column - prev_source_column);
        prev_source_column = s.column;
        if (m.name != Mapping.no_name) {
            vlqAssumeCapacity(out, @as(i64, m.name) - prev_name);
            prev_name = m.name;
        }
        segment_on_line = true;
    }
}

const block = 16;
const Block = @Vector(block, u8);

/// Whether the two scans below skip sixteen bytes at a time. Only where
/// LLVM compiles them: Zig's own backend writes a vector operation as a
/// loop over its lanes, so a block cost thousands of instructions where
/// sixteen bytes one at a time cost a hundred — a third of a development
/// build of a page was its maps' `sourcesContent`. The two paths find the
/// same bytes; only how fast they skip the ones that need nothing differs.
const use_blocks = builtin.zig_backend == .stage2_llvm;

/// UTF-16 code units for a UTF-8 lead byte: two for a four-byte sequence,
/// none for a continuation byte, one otherwise.
inline fn utf16Units(c: u8) u32 {
    if (c & 0xC0 == 0x80) return 0;
    return if (c >= 0xF0) 2 else 1;
}

const Position = struct { line: i64, column: i64 };

/// The source side: 0-based line and UTF-16 column of a byte offset.
///
/// A column is a byte difference less what the bytes past ASCII before it
/// on its line take back: every such byte is listed once, with the running
/// total of `1 - utf16Units` up to it (`shrink`), so a column is two binary
/// searches whatever order the marks come in — one line of 4 097 marks, the
/// generated order jumping back and forth along it, costs no rescan. An
/// all-ASCII source lists nothing and a column is the byte difference.
const SourceLines = struct {
    source: []const u8,
    line_starts: []const u32,
    /// The offset of every byte past ASCII, ascending.
    wide: []const u32,
    /// `shrink[i]`: the bytes `wide[0..i + 1]` count more than the UTF-16
    /// units they make. A running total can dip below zero inside a
    /// four-byte sequence, whose lead byte makes two units.
    shrink: []const i32,
    /// The line of the last offset asked about.
    hint: usize = 0,

    fn init(scratch: Allocator, source: []const u8, line_starts: []const u32) Allocator.Error!SourceLines {
        var count: usize = 0;
        for (source) |c| count += @intFromBool(c >= 0x80);
        const wide = try scratch.alloc(u32, count);
        const shrink = try scratch.alloc(i32, count);
        var k: usize = 0;
        var total: i32 = 0;
        for (source, 0..) |c, i| {
            if (c < 0x80) continue;
            total += 1 - @as(i32, @intCast(utf16Units(c)));
            wide[k] = @intCast(i);
            shrink[k] = total;
            k += 1;
        }
        return .{ .source = source, .line_starts = line_starts, .wide = wide, .shrink = shrink };
    }

    /// What the bytes past ASCII before `offset` take back from a column.
    fn shrinkBefore(s: *const SourceLines, offset: usize) i64 {
        // `std.sort.lowerBound`, written out: the first `wide` at or past
        // `offset`. Twice per mark, and the generic search's comparator is a
        // call per step where Zig's own backend compiles the compiler.
        var lo: usize = 0;
        var hi: usize = s.wide.len;
        while (lo < hi) {
            const mid = lo + (hi - lo) / 2;
            if (s.wide[mid] < offset) lo = mid + 1 else hi = mid;
        }
        return if (lo == 0) 0 else s.shrink[lo - 1];
    }

    /// Whether `offset` is on 0-based line `line`.
    fn within(s: *const SourceLines, line: usize, offset: u32) bool {
        if (line >= s.line_starts.len or s.line_starts[line] > offset) return false;
        return line + 1 == s.line_starts.len or offset < s.line_starts[line + 1];
    }

    fn position(s: *SourceLines, offset: u32) Position {
        if (s.line_starts.len == 0) return .{ .line = 0, .column = 0 };
        // The line of the mark before, or the one after it, nearly always:
        // marks follow the source within a declaration.
        var lo: usize = s.hint;
        if (!s.within(lo, offset)) {
            lo += 1;
            if (!s.within(lo, offset)) {
                lo = 0;
                var hi: usize = s.line_starts.len;
                while (hi - lo > 1) {
                    const mid = lo + (hi - lo) / 2;
                    if (s.line_starts[mid] <= offset) lo = mid else hi = mid;
                }
            }
        }
        s.hint = lo;
        const start = @min(@as(usize, s.line_starts[lo]), s.source.len);
        const end = @max(start, @min(@as(usize, offset), s.source.len));
        const bytes: i64 = @intCast(end - start);
        if (s.wide.len == 0) return .{ .line = @intCast(lo), .column = bytes };
        return .{ .line = @intCast(lo), .column = bytes - (s.shrinkBefore(end) - s.shrinkBefore(start)) };
    }
};

const base64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/// One Base64 VLQ: the sign in the lowest bit, five bits per digit, the
/// sixth bit set on every digit but the last.
fn vlq(scratch: Allocator, out: *std.ArrayList(u8), value: i64) Allocator.Error!void {
    try out.ensureUnusedCapacity(scratch, max_vlq_digits);
    vlqAssumeCapacity(out, value);
}

/// A 64-bit value with its sign bit takes at most 13 five-bit digits.
const max_vlq_digits = 13;

fn vlqAssumeCapacity(out: *std.ArrayList(u8), value: i64) void {
    var v: u64 = if (value < 0) (@as(u64, @intCast(-value)) << 1) | 1 else @as(u64, @intCast(value)) << 1;
    // The common case, a delta under 16 either way: one digit.
    if (v < 32) return out.appendAssumeCapacity(base64[@intCast(v)]);
    while (true) {
        var digit: u8 = @intCast(v & 31);
        v >>= 5;
        if (v != 0) digit |= 32;
        out.appendAssumeCapacity(base64[digit]);
        if (v == 0) return;
    }
}

/// `text` as a JSON string: `"`, `\` and the control characters escaped,
/// everything else — UTF-8 included — as it is.
fn jsonString(scratch: Allocator, out: *std.ArrayList(u8), text: []const u8) Allocator.Error!void {
    try out.append(scratch, '"');
    var run: usize = 0;
    var i: usize = 0;
    while (i < text.len) : (i += 1) {
        // Sixteen bytes at a time while none needs an escape.
        while (use_blocks and text.len - i >= block) {
            const v: Block = text[i..][0..block].*;
            const special = (v < @as(Block, @splat(0x20))) | (v == @as(Block, @splat('"'))) | (v == @as(Block, @splat('\\')));
            if (@reduce(.Or, special)) break;
            i += block;
        }
        if (i == text.len) break;
        const c = text[i];
        if (c >= 0x20 and c != '"' and c != '\\') continue;
        try out.appendSlice(scratch, text[run..i]);
        run = i + 1;
        switch (c) {
            '"' => try out.appendSlice(scratch, "\\\""),
            '\\' => try out.appendSlice(scratch, "\\\\"),
            '\n' => try out.appendSlice(scratch, "\\n"),
            '\r' => try out.appendSlice(scratch, "\\r"),
            '\t' => try out.appendSlice(scratch, "\\t"),
            else => {
                var buf: [6]u8 = undefined;
                try out.appendSlice(scratch, std.fmt.bufPrint(&buf, "\\u{x:0>4}", .{c}) catch unreachable);
            },
        }
    }
    try out.appendSlice(scratch, text[run..]);
    try out.append(scratch, '"');
}

/// The URL of `source_path` relative to the directory of the map at
/// `map_path`, both absolute and lexically normal (`/`-separated, no `.`
/// or `..` segment). A path that shares no directory with the map's climbs
/// to the root.
pub fn relativeUrl(scratch: Allocator, map_path: []const u8, source_path: []const u8) Allocator.Error![]const u8 {
    const map_dir = std.fs.path.dirnamePosix(map_path) orelse "";
    var from = std.mem.tokenizeScalar(u8, map_dir, '/');
    var to = std.mem.tokenizeScalar(u8, source_path, '/');
    var from_rest: ?[]const u8 = null;
    var to_rest: ?[]const u8 = null;
    while (true) {
        from_rest = from.next();
        to_rest = to.next();
        const a = from_rest orelse break;
        const b = to_rest orelse break;
        if (!std.mem.eql(u8, a, b)) break;
    }
    var out: std.ArrayList(u8) = .empty;
    if (from_rest != null) {
        try out.appendSlice(scratch, "../");
        while (from.next() != null) try out.appendSlice(scratch, "../");
    }
    if (to_rest) |first| {
        try out.appendSlice(scratch, first);
        while (to.next()) |segment| {
            try out.append(scratch, '/');
            try out.appendSlice(scratch, segment);
        }
    }
    return out.items;
}

/// `path` made absolute against `cwd` (itself absolute) and lexically
/// normal: `.` segments dropped, `..` taking the segment before it.
pub fn absolute(scratch: Allocator, cwd: []const u8, path: []const u8) Allocator.Error![]const u8 {
    var segments: std.ArrayList([]const u8) = .empty;
    const parts: [2][]const u8 = .{ if (std.fs.path.isAbsolutePosix(path)) "" else cwd, path };
    for (parts) |part| {
        var it = std.mem.tokenizeScalar(u8, part, '/');
        while (it.next()) |segment| {
            if (std.mem.eql(u8, segment, ".")) continue;
            if (std.mem.eql(u8, segment, "..")) {
                _ = segments.pop();
                continue;
            }
            try segments.append(scratch, segment);
        }
    }
    var out: std.ArrayList(u8) = .empty;
    for (segments.items) |segment| {
        try out.append(scratch, '/');
        try out.appendSlice(scratch, segment);
    }
    if (out.items.len == 0) try out.append(scratch, '/');
    return out.items;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

fn expectVlq(expected: []const u8, value: i64) !void {
    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(testing.allocator);
    try vlq(testing.allocator, &out, value);
    try testing.expectEqualStrings(expected, out.items);
}

test "a VLQ digit carries five bits and the sign rides in the lowest" {
    try expectVlq("A", 0);
    try expectVlq("C", 1);
    try expectVlq("D", -1);
    try expectVlq("e", 15);
    try expectVlq("gB", 16);
    try expectVlq("hB", -16);
    try expectVlq("2H", 123);
    try expectVlq("+8D", 1999);
}

test "a source URL is relative to the map's directory" {
    var a: std.heap.ArenaAllocator = .init(testing.allocator);
    defer a.deinit();
    const arena = a.allocator();
    try testing.expectEqualStrings("../src/Main.beni", try relativeUrl(arena, "/p/out/Main.mjs.map", "/p/src/Main.beni"));
    try testing.expectEqualStrings("../../src/A/B.beni", try relativeUrl(arena, "/p/out/A/B.mjs.map", "/p/src/A/B.beni"));
    try testing.expectEqualStrings("Main.beni", try relativeUrl(arena, "/p/Main.mjs.map", "/p/Main.beni"));
    try testing.expectEqualStrings("../x/Main.beni", try relativeUrl(arena, "/a/Main.mjs.map", "/x/Main.beni"));
    try testing.expectEqualStrings("/p/x", try absolute(arena, "/p/q", "../x"));
    try testing.expectEqualStrings("/p/q/src/A.beni", try absolute(arena, "/p/q", "./src/A.beni"));
    try testing.expectEqualStrings("/abs/A.beni", try absolute(arena, "/p", "/abs/A.beni"));
}

test "columns count UTF-16 units on both sides, and a line ends at U+2028" {
    var a: std.heap.ArenaAllocator = .init(testing.allocator);
    defer a.deinit();
    const arena = a.allocator();
    // Generated: `"é😀";x` then U+2028 then `y`. Source: `é😀 z`.
    const generated = "\"\xc3\xa9\xf0\x9f\x98\x80\";x\xe2\x80\xa8y";
    const source = "\xc3\xa9\xf0\x9f\x98\x80 z";
    const nothing = struct {
        fn f(_: *const anyopaque, _: InternPool.Symbol) []const u8 {
            return "";
        }
    }.f;
    const text = try write(arena, arena, .{
        .file = "M.mjs",
        .source_url = "M.beni",
        .source = source,
        .line_starts = &.{0},
        .generated = generated,
        // `x` is at UTF-16 column 6 (`"`, é, two for 😀, `"`, `;`); `z` at 4.
        .mappings = &.{
            .{ .generated = 9, .source = 7 },
            .{ .generated = 13, .source = 0 },
        },
        .names = &.{},
        .name_text = .{ .context = undefined, .lookup = nothing },
    });
    try testing.expectEqualStrings(
        "{\"version\":3,\"file\":\"M.mjs\",\"sources\":[\"M.beni\"],\"sourcesContent\":[\"\xc3\xa9\xf0\x9f\x98\x80 z\"],\"names\":[],\"mappings\":\"MAAI;AAAJ\"}\n",
        text,
    );
}

test "a source column is right whatever order the marks on its line come in" {
    // `λa → b`: `b` is UTF-16 column 5 and `a` column 1. The marks come
    // right to left, which once made each one rescan the line from its
    // start.
    var a: std.heap.ArenaAllocator = .init(testing.allocator);
    defer a.deinit();
    const arena = a.allocator();
    const nothing = struct {
        fn f(_: *const anyopaque, _: InternPool.Symbol) []const u8 {
            return "";
        }
    }.f;
    const text = try write(arena, arena, .{
        .file = "M.mjs",
        .source_url = "M.beni",
        .source = "λa → b",
        .line_starts = &.{0},
        .generated = "xy",
        .mappings = &.{
            .{ .generated = 0, .source = 8 },
            .{ .generated = 1, .source = 2 },
        },
        .names = &.{},
        .name_text = .{ .context = undefined, .lookup = nothing },
    });
    try testing.expect(std.mem.endsWith(u8, text, "\"mappings\":\"AAAK,CAAJ\"}\n"));
}
