// Compiles `Rt.beni` (the slot and mount half of the browser runtime,
// written in beni over core's `Js`) and writes `../beni-runtime/runtime.js`:
// the compiled half, then `runtime.rest.js`, the half still hand-written.
// Research 47, a spike.
//
//   node splice.mjs [--beni=<path to beni>] [--release-src]
//
// The compiled half is beni's development output with its module plumbing
// taken off: `Rt$x` is spelled `x`, which is the name the hand-written half
// and the `dom` lowering call it by; the few core functions it calls
// (`Basics.add` and `Basics.sub`, which beni does not write as operators)
// are copied in from core's sibling; `import` and `export` lists go, and
// the five functions the runtime exports are `export const`.

import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "../../..");
const arg = (name, fallback) => process.argv.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3) ?? fallback;
const beni = arg("beni", join(repo, "zig-out/bin/beni"));

const compile = (release) => {
  const out = mkdtempSync(join(tmpdir(), "beni-rt-"));
  const r = spawnSync(beni, ["build", "--platform=node", "--library", ...(release ? ["--release"] : []), "--no-cache", `--out=${out}`, "Rt.beni"], { cwd: here, encoding: "utf8" });
  if (r.status !== 0) {
    process.stderr.write(r.stdout + r.stderr);
    process.exit(1);
  }
  const text = readFileSync(join(out, "Rt.mjs"), "utf8");
  rmSync(out, { recursive: true, force: true });
  return text;
};
let js = compile(false);
const basics = readFileSync(join(repo, "core/Basics.js"), "utf8");
const exported = ["template", "slot", "childHtml", "flush", "run"];

// `--release-src`: beni's own release optimiser over the port (short names,
// joined `const`s, compact printing), as it would be were the runtime
// compiled with the program rather than ahead of it. Its names are mapped
// back through the development build's `import` and `export` lists, which
// list the same names in the same order.
if (process.argv.includes("--release-src")) {
  const dev = js;
  let rel = compile(true);
  const devImports = (dev.match(/^import \{([^}]*)\} from "\.\/_core\/Basics\.mjs";$/m)?.[1] ?? "").split(",").map((s) => s.trim().replace(/^Basics\$/, "")).filter((s) => s !== "");
  const devExports = dev.match(/^export \{([^}]*)\};$/m)[1].split(",").map((s) => s.trim().replace(/^Rt\$/, ""));
  const relImports = (rel.match(/^import\{([^}]*)\}from"\.\/_core\/Basics\.mjs";$/m)?.[1] ?? "").split(",").filter((s) => s !== "");
  const relExports = rel.match(/^export\{([^}]*)\};$/m)[1].split(",");
  rel = rel.replace(/^import\{[^}]*\}from"[^"]*";\n/m, "").replace(/^export\{[^}]*\};\n?/m, "");
  // One declaration per statement: check 3 reads a `const` list as its
  // first name only.
  rel = rel.replace(/,\n(?=[A-Za-z_$][\w$]*=)/g, ";\nconst ");
  const lines = [];
  devImports.forEach((n, k) => {
    const m = basics.match(new RegExp(`^export const ${n} = (.*);$`, "m"));
    lines.push(`const ${relImports[k]}=${m[1]};`);
  });
  // An export is declared under its own name, its short name an alias of
  // it; every other name the hand-written half calls is an alias.
  const aliases = [];
  const esc = (s) => s.replace(/\$/g, "\\$");
  devExports.forEach((n, k) => {
    const short = relExports[k];
    if (exported.includes(n)) {
      const head = new RegExp(`^(const |)${esc(short)}=`, "m");
      if (!head.test(rel)) throw new Error(`no declaration of ${short} (${n})`);
      rel = rel.replace(head, `export const ${n}=`);
      aliases.push(`${short}=${n}`);
    } else aliases.push(`${n}=${short}`);
  });
  // `flush`'s unread unit parameter, as below.
  rel = rel.replace(/^export const flush=\(a\)=>/m, "export const flush=()=>");
  js = `${lines.join("\n")}\n${rel}${aliases.map((a) => `const ${a};`).join("\n")}\n`;
  const rest = readFileSync(join(here, "runtime.rest.js"), "utf8");
  writeFileSync(join(here, "../beni-runtime/runtime.js"), `// GENERATED by splice.mjs --release-src (research 47); see splice.mjs.\n${js}\n${rest}`);
  console.log("wrote tests/platforms/beni-runtime/runtime.js (release-compiled port)");
  process.exit(0);
}

// The core functions it imports, from core's sibling.
const prelude = [];
js = js.replace(/^import \{([^}]*)\} from "\.\/_core\/Basics\.mjs";\n/m, (_, names) => {
  for (const n of names.split(",").map((s) => s.trim().replace(/^Basics\$/, ""))) {
    const m = basics.match(new RegExp(`^export const ${n} = (.*);$`, "m"));
    if (m === null) throw new Error(`Basics.${n} is not a one-line export of core/Basics.js`);
    prelude.push(`const Basics$${n} = ${m[1]};`);
  }
  return "";
});
if (/^import /m.test(js)) throw new Error("Rt.mjs imports something other than Basics");
js = js.replace(/^export \{[^}]*\};\n/m, "");
js = js.replace(/\bRt\$(\w+)/g, "$1");
for (const e of exported) {
  js = js.replace(new RegExp(`^const ${e} = `, "m"), `export const ${e} = `);
}
// beni has no function of no parameters: `flush : () -> ()` takes a unit
// it never reads, `($p$n) =>`, and the lowering calls it with none, which
// check 4 refuses. The unread parameter goes.
js = js.replace(/^export const flush = \(\$p\$\d+\) =>/m, "export const flush = () =>");

const header = `// GENERATED by tests/platforms/beni-runtime-src/splice.mjs — do not edit.
//
// The browser platform's runtime (platforms/browser/runtime.js) with its
// slot and mount half — instances and their nodes, templates, slots, the
// render loop and the mount — compiled from tests/platforms/beni-runtime-src/Rt.beni,
// beni written over core's \`Js\` (docs/design/research/47). The rest,
// from \`childMaybe\` on, is the hand-written runtime's, unchanged.

`;
const rest = readFileSync(join(here, "runtime.rest.js"), "utf8");
writeFileSync(join(here, "../beni-runtime/runtime.js"), `${header}${prelude.join("\n")}\n${js}\n${rest}`);
console.log("wrote tests/platforms/beni-runtime/runtime.js");
