// Shared pieces of the scaling sweeps' generated programs (scaling.mjs).
// Every sweep writes, for one value of its parameter, one program per
// framework: `Main.beni` (built twice, development and `--release`),
// `solid1.jsx`, `solid2.jsx`, `p2.js` and `vanilla.js`. Each is the program
// a developer would write for that framework; nothing in one is shaped to
// win or lose a measurement.

import { readFileSync } from "node:fs";

export const range = (n) => Array.from({ length: n }, (_, i) => i);
export const chunks = (xs, size) => range(Math.ceil(xs.length / size)).map((i) => xs.slice(i * size, (i + 1) * size));
export const indent = (text, n) =>
  text
    .split("\n")
    .map((l) => (l === "" ? l : " ".repeat(n) + l))
    .join("\n");

export const beniHeader = (what) => `-- Generated by bench/ui/scaling.mjs: ${what}.
import Browser
import Html exposing (Html)
import Tea


`;

// Solid 1 and Solid 2 differ in where `render` and `createStore` come from:
// Solid 2 moved the DOM half to @solidjs/web and the store into solid-js.
export const solidHeader = (v, what, imports, store = []) => {
  const core = v === 1 ? imports : [...imports, ...store];
  const lines = [`// Generated by bench/ui/scaling.mjs: ${what}, Solid ${v}.`];
  if (core.length > 0) lines.push(`import { ${core.join(", ")} } from "solid-js";`);
  if (v === 1 && store.length > 0) lines.push(`import { ${store.join(", ")} } from "solid-js/store";`);
  lines.push(`import { render } from "${v === 1 ? "solid-js/web" : "@solidjs/web"}";`);
  return `${lines.join("\n")}\n`;
};

export const solidMount = (app) => `render(() => ${app}, document.getElementById("main"));\n`;

// The keyed list hole of P2 (apps/p2/bench.js, research 29 §7.1) made
// generic over the row: `makeListHole(parent, key, make, patch)`.
export const p2List = readFileSync(new URL("./p2-list.js", import.meta.url), "utf8");

// One root for the plain-script subjects, which bring no `<div id="main">`.
export const scriptRoot = `const root = document.createElement("div");
root.className = "container";
document.body.appendChild(root);
`;
