// Sweep 4, model depth: the value that changes sits D records deep. Each
// level is its own record type with a label, shown by its own view helper
// (in Solid, its own component), the way a nested model is written; `#go`
// adds one to the innermost value, so every level on the path is rebuilt
// by an update helper of its own. Solid keeps the tree in a store.

import { beniHeader, range, scriptRoot, solidHeader, solidMount } from "./common.mjs";

const levels = (d) => range(d).map((i) => i + 1);

export const beni = (d) => {
  const ls = levels(d);
  const types = ls
    .map((k) =>
      k === d
        ? `type alias N${k} =\n    label : String\n    v : Int`
        : `type alias N${k} =\n    label : String\n    child : N${k + 1}`,
    )
    .join("\n\n\n");
  const inits = ls
    .map((k) => `init${k} : N${k}\ninit${k} = { label = "level ${k}", ${k === d ? "v = 0" : `child = init${k + 1}`} }`)
    .join("\n\n\n");
  const bumps = ls
    .map((k) => `bump${k} : N${k} → N${k}\nbump${k} n = ${k === d ? "{ n | v = n.v + 1 }" : `{ n | child = bump${k + 1} n.child }`}`)
    .join("\n\n\n");
  const views = ls
    .map(
      (k) => `view${k} : N${k} → Html Msg
view${k} n =
    <div class="level">
        <span>{n.label}</span>
        ${k === d ? '<b id="v">{n.v}</b>' : `{view${k + 1} n.child}`}
    </div>`,
    )
    .join("\n\n\n");
  return `${beniHeader(`model depth, ${d} levels`)}${types}


type alias Model =
    root : N1


type Msg
    = Go


${inits}


${bumps}


update : Msg, Model → Model
update msg model =
    case msg of
        Go →
            { model | root = bump1 model.root }


${views}


view : Model → Html Msg
view model =
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
        {view1 model.root}
    </div>


main : Browser.Program
main = Tea.sandbox { init = { root = init1 }, update = update, view = view }
`;
};

const jsInit = (d) => `(() => {
  let n = { label: "level ${d}", v: 0 };
  for (let k = ${d - 1}; k >= 1; k--) n = { label: \`level \${k}\`, child: n };
  return n;
})()`;

export const solid = (v, d) => {
  const ls = levels(d);
  const comps = ls
    .map((k) =>
      k === d
        ? `const L${k} = (props) => (\n  <div class="level">\n    <span>{props.n.label}</span>\n    <b id="v">{props.n.v}</b>\n  </div>\n);`
        : `const L${k} = (props) => (\n  <div class="level">\n    <span>{props.n.label}</span>\n    <L${k + 1} n={props.n.child} />\n  </div>\n);`,
    )
    .reverse()
    .join("\n");
  const path = range(d - 1).map(() => "child");
  const go = v === 1 ? `setS(${["root", ...path, "v"].map((p) => JSON.stringify(p)).join(", ")}, (x) => x + 1)` : `setS((s) => {\n    s.root${path.map((p) => `.${p}`).join("")}.v += 1;\n  })`;
  return `${solidHeader(v, `model depth, ${d} levels`, [], ["createStore"])}
${comps}

const App = () => {
  const [s, setS] = createStore({ root: ${jsInit(d)} });
  const go = () => ${go};
  return (
    <div class="container">
      <button type="button" id="go" onClick={go}>go</button>
      <L1 n={s.root} />
    </div>
  );
};

${solidMount("<App />")}`;
};

// P2: the update rebuilds the path with spreads; the view is a helper per
// level that keeps what it showed when its record is the same object.
export const p2 = (d) => `// Generated by bench/ui/scaling.mjs: model depth, ${d} levels, P2.
${scriptRoot}const D = ${d};
let model = { root: ${jsInit(d)} };
const bump = (n, k) => (k === D ? { ...n, v: n.v + 1 } : { ...n, child: bump(n.child, k + 1) });
const update = (msg, m) => (msg === "Go" ? { ...m, root: bump(m.root, 1) } : m);
const mount = (parent, n, k) => {
  const div = document.createElement("div");
  div.className = "level";
  const span = document.createElement("span");
  const label = document.createTextNode(n.label);
  span.appendChild(label);
  div.appendChild(span);
  parent.appendChild(div);
  const inst = { n, label };
  if (k === D) {
    const b = document.createElement("b");
    b.id = "v";
    inst.v = document.createTextNode(n.v);
    b.appendChild(inst.v);
    div.appendChild(b);
  } else inst.child = mount(div, n.child, k + 1);
  return inst;
};
const patch = (inst, n, k) => {
  if (inst.n === n) return;
  if (inst.n.label !== n.label) inst.label.data = n.label;
  if (k === D) {
    if (inst.n.v !== n.v) inst.v.data = n.v;
  } else patch(inst.child, n.child, k + 1);
  inst.n = n;
};
root.innerHTML = '<button type="button" id="go">go</button>';
const rootInst = mount(root, model.root, 1);
document.getElementById("go").addEventListener("click", () => {
  model = update("Go", model);
  patch(rootInst, model.root, 1);
});
`;

export const vanilla = (d) => `// Generated by bench/ui/scaling.mjs: model depth, ${d} levels, vanilla.
${scriptRoot}const state = { root: ${jsInit(d)} };
root.innerHTML = '<button type="button" id="go">go</button>';
let parent = root;
let leaf = null;
for (let n = state.root; n !== undefined; n = n.child) {
  const div = document.createElement("div");
  div.className = "level";
  div.innerHTML = "<span></span>";
  div.firstChild.textContent = n.label;
  parent.appendChild(div);
  if (n.child === undefined) {
    const b = document.createElement("b");
    b.id = "v";
    b.textContent = n.v;
    div.appendChild(b);
    leaf = n;
  }
  parent = div;
}
const vText = document.getElementById("v").firstChild;
document.getElementById("go").addEventListener("click", () => {
  leaf.v += 1;
  vText.data = leaf.v;
});
`;
