// Sweep 5, derived computation: N items, of which the view shows a
// projection — the active ones, sorted by score, the first 50 — while
// `#go` changes only an unrelated counter. Solid derives the projection in
// a `createMemo`. beni's idiomatic program derives it in `view`, so it is
// recomputed on every render; `beniHelper` is the same program with the
// table in a view helper, `{viewTop model.items}`, whose call a render
// skips while `model.items` is the same list (language.md §11.6).

import { beniHeader, p2List, scriptRoot, solidHeader, solidMount } from "./common.mjs";

export const SHOWN = 50;

const beniTop = `top : List Item → List Item
top items = List.take (List.sortBy (List.filter items .active) .score) ${SHOWN}`;

const beniTable = (each) => `<table class="table table-hover table-striped test-data">
    <tbody>
        <For each={${each}} keyed={.id}>
            {λitem →
                <tr>
                    <td class="col-md-1">{item.id}</td>
                    <td class="col-md-4">{item.score}</td>
                </tr>
            }
        </For>
    </tbody>
</table>`;

const beniCommon = (n) => `type alias Item =
    id : Int
    score : Int
    active : Bool


type alias Model =
    items : List Item
    tick : Int


type Msg
    = Go


update : Msg, Model → Model
update msg model =
    case msg of
        Go →
            { model | tick = model.tick + 1 }


makeItem : Int → Item
makeItem i = { id = i, score = Int.mod (i * 7919 + 13) 100003, active = Int.mod i 2 == 0 }


${beniTop}
`;

const beniMain = (n) => `main : Browser.Program
main =
    Tea.sandbox
        { init = { items = List.initialize ${n} makeItem, tick = 0 }
        , update = update
        , view = view
        }
`;

const shift = (text, n) =>
  text
    .split("\n")
    .map((l, i) => (i === 0 || l === "" ? l : " ".repeat(n) + l))
    .join("\n");

export const beni = (n) => `${beniHeader(`derived computation, ${n} items, derived in view`)}${beniCommon(n)}

view : Model → Html Msg
view model =
    shown = top model.items
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
        <p id="tick">{model.tick}</p>
        ${shift(beniTable("shown"), 8)}
    </div>


${beniMain(n)}`;

export const beniHelper = (n) => `${beniHeader(`derived computation, ${n} items, the table in a view helper`)}${beniCommon(n)}

viewTop : List Item → Html Msg
viewTop items =
    ${shift(beniTable("top items"), 4)}


view : Model → Html Msg
view model =
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
        <p id="tick">{model.tick}</p>
        {viewTop model.items}
    </div>


${beniMain(n)}`;

const jsItems = (n) => `Array.from({ length: ${n} }, (_, i) => ({ id: i, score: (i * 7919 + 13) % 100003, active: i % 2 === 0 }))`;
const jsTop = `(items) => items.filter((i) => i.active).sort((a, b) => a.score - b.score).slice(0, ${SHOWN})`;

export const solid = (v, n) => `${solidHeader(v, `derived computation, ${n} items`, ["createMemo", "createSignal", "For"])}
const topOf = ${jsTop};

const App = () => {
  const [items] = createSignal(${jsItems(n)});
  const [tick, setTick] = createSignal(0);
  const shown = createMemo(() => topOf(items()));
  return (
    <div class="container">
      <button type="button" id="go" onClick={() => setTick((t) => t + 1)}>go</button>
      <p id="tick">{tick()}</p>
      <table class="table table-hover table-striped test-data">
        <tbody>
          <For each={shown()}>
            {(item) => (
              <tr>
                <td class="col-md-1" textContent={item.id} />
                <td class="col-md-4" textContent={item.score} />
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  );
};

${solidMount("<App />")}`;

const shell = '<button type="button" id="go">go</button><p id="tick"> </p><table class="table table-hover table-striped test-data"><tbody></tbody></table>';
const rowHtml = '<tr><td class="col-md-1"> </td><td class="col-md-4"> </td></tr>';

// P2 derives in its view, as beni's idiomatic program does.
export const p2 = (n) => `// Generated by bench/ui/scaling.mjs: derived computation, ${n} items, P2.
${p2List}
${scriptRoot}root.innerHTML = ${JSON.stringify(shell)};
const tickT = document.getElementById("tick").firstChild;
const tpl = document.createElement("template");
tpl.innerHTML = ${JSON.stringify(rowHtml)};
const proto = tpl.content.firstChild;
const make = (item) => {
  const el = proto.cloneNode(true);
  const idT = el.firstChild.firstChild;
  const scT = el.firstChild.nextSibling.firstChild;
  idT.data = item.id;
  scT.data = item.score;
  return { el, item, idT, scT };
};
const patch = (inst, item) => {
  if (inst.item.id !== item.id) inst.idT.data = item.id;
  if (inst.item.score !== item.score) inst.scT.data = item.score;
};
const list = makeListHole(root.querySelector("tbody"), make, patch);
const topOf = ${jsTop};
let model = { items: ${jsItems(n)}, tick: 0 };
let lastTick;
const update = (msg, m) => (msg === "Go" ? { ...m, tick: m.tick + 1 } : m);
const render = (m) => {
  if (m.tick !== lastTick) tickT.data = lastTick = m.tick;
  list(topOf(m.items));
};
render(model);
document.getElementById("go").addEventListener("click", () => {
  model = update("Go", model);
  render(model);
});
`;

export const vanilla = (n) => `// Generated by bench/ui/scaling.mjs: derived computation, ${n} items, vanilla.
${scriptRoot}root.innerHTML = ${JSON.stringify(shell)};
const tickT = document.getElementById("tick").firstChild;
const tbody = root.querySelector("tbody");
const tpl = document.createElement("template");
tpl.innerHTML = ${JSON.stringify(rowHtml)};
const proto = tpl.content.firstChild;
const items = ${jsItems(n)};
for (const item of (${jsTop})(items)) {
  const tr = proto.cloneNode(true);
  tr.firstChild.firstChild.data = item.id;
  tr.firstChild.nextSibling.firstChild.data = item.score;
  tbody.appendChild(tr);
}
let tick = 0;
tickT.data = tick;
document.getElementById("go").addEventListener("click", () => {
  tick++;
  tickT.data = tick;
});
`;
