// Sweep 1, view size: a page of N dynamic holes, one of which — a ticking
// counter — changes per message. The other N - 1 read three values of the
// model that never change: a text, a number and a class, in turn, ten
// holes to a `<section>`. Sweep 6 (bursts and a sustained stream) uses the
// same page.

import { beniHeader, chunks, indent, p3Loop, p3Root, range, scriptRoot, solidHeader, solidMount } from "./common.mjs";

// Hole k of the N - 1 still ones: 0 a text, 1 a number, 2 a class.
const still = (n) => range(n - 1).map((k) => k % 3);

const beniHole = (kind) => (kind === 0 ? "<p>{model.name}</p>" : kind === 1 ? "<p>{model.count}</p>" : '<p class={model.cls}>x</p>');
const solidHole = (kind) => (kind === 0 ? "<p>{name()}</p>" : kind === 1 ? "<p>{count()}</p>" : '<p class={cls()}>x</p>');
const sections = (n, hole) =>
  chunks(still(n), 10)
    .map((ks) => `<section>\n${ks.map((k) => `    ${hole(k)}`).join("\n")}\n</section>`)
    .join("\n");

export const beni = (n) => `${beniHeader(`view size, ${n} holes`)}type alias Model =
    tick : Int
    name : String
    count : Int
    cls : String


type Msg
    = Go


update : Msg, Model → Model
update msg model =
    case msg of
        Go →
            { model | tick = model.tick + 1 }


view : Model → Html Msg
view model =
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
        <p id="tick">{model.tick}</p>
${indent(sections(n, beniHole), 8)}
    </div>


main : Browser.Program
main =
    Tea.sandbox
        { init = { tick = 0, name = "beni", count = 7, cls = "c" }
        , update = update
        , view = view
        }
`;

export const solid = (v, n) => `${solidHeader(v, `view size, ${n} holes`, ["createSignal"])}
const App = () => {
  const [tick, setTick] = createSignal(0);
  const [name] = createSignal("beni");
  const [count] = createSignal(7);
  const [cls] = createSignal("c");
  return (
    <div class="container">
      <button type="button" id="go" onClick={() => setTick((t) => t + 1)}>go</button>
      <p id="tick">{tick()}</p>
${indent(sections(n, solidHole), 6)}
    </div>
  );
};

${solidMount("<App />")}`;

// P2 by hand: one template, the model updated by a spread, and every hole
// compared with the value it last wrote on every render, as beni's
// compiled `view` does.
export const p2 = (n) => {
  const kinds = still(n);
  const html = `<button type="button" id="go">go</button><p id="tick"> </p>${chunks(kinds, 10)
    .map((ks) => `<section>${ks.map((k) => (k === 2 ? "<p>x</p>" : "<p> </p>")).join("")}</section>`)
    .join("")}`;
  const lines = kinds.map((k, i) =>
    k === 0 ? `  if ((x = m.name) !== v[${i + 1}]) h[${i + 1}].data = v[${i + 1}] = x;` : k === 1 ? `  if ((x = m.count) !== v[${i + 1}]) h[${i + 1}].data = v[${i + 1}] = x;` : `  if ((x = m.cls) !== v[${i + 1}]) h[${i + 1}].className = v[${i + 1}] = x;`,
  );
  return `// Generated by bench/ui/scaling.mjs: view size, ${n} holes, P2.
${scriptRoot}const tpl = document.createElement("template");
tpl.innerHTML = ${JSON.stringify(html)};
root.appendChild(tpl.content.cloneNode(true));
const ps = root.querySelectorAll("p");
const kinds = ${JSON.stringify([0, ...kinds.map((k) => (k === 2 ? 1 : 0))])};
const h = Array.from(ps, (p, i) => (kinds[i] === 1 ? p : p.firstChild));
const v = new Array(h.length);
let model = { tick: 0, name: "beni", count: 7, cls: "c" };
const update = (msg, m) => (msg === "Go" ? { ...m, tick: m.tick + 1 } : m);
function render(m) {
  let x;
  if ((x = m.tick) !== v[0]) h[0].data = v[0] = x;
${lines.join("\n")}
}
render(model);
document.getElementById("go").addEventListener("click", () => {
  model = update("Go", model);
  render(model);
});
`;
};

// Vanilla: the page written once, the counter's text node kept and written.
export const vanilla = (n) => {
  const html = `<button type="button" id="go">go</button><p id="tick">0</p>${chunks(still(n), 10)
    .map((ks) => `<section>${ks.map((k) => (k === 0 ? "<p>beni</p>" : k === 1 ? "<p>7</p>" : '<p class="c">x</p>')).join("")}</section>`)
    .join("")}`;
  return `// Generated by bench/ui/scaling.mjs: view size, ${n} holes, vanilla.
${scriptRoot}root.innerHTML = ${JSON.stringify(html)};
const tickText = document.getElementById("tick").firstChild;
let tick = 0;
document.getElementById("go").addEventListener("click", () => {
  tick++;
  tickText.data = tick;
});
`;
};

// P3 (research 60): message-indexed rendering. W2: no branch writes `name`,
// `count` or `cls`, and `init` gives each a literal, so their N - 1 holes are
// template text, written as beni writes a template. `tick` is written by
// `Go`: one group, whose slot starts at `init`'s literal, which the
// template also holds. W1(Go) = {tick}, W3(Go) = {the tick group}.
export const p3 = (n) => {
  const html = `<div class=container><button type=button id=go>go</button><p id=tick>0</p>${chunks(still(n), 10)
    .map((ks) => `<section>${ks.map((k) => (k === 0 ? "<p>beni</p>" : k === 1 ? "<p>7</p>" : "<p class=c>x</p>")).join("")}</section>`)
    .join("")}</div>`;
  return `// Generated by bench/ui/scaling.mjs: view size, ${n} holes, P3 (research 60).
${p3Loop}
let model = { cls: "c", count: 7, name: "beni", tick: 0 };
${p3Root(html)}const go = root.firstChild;
const w0 = go.nextSibling.firstChild;
let g0 = 0;
const Go = () => {
  model = { ...model, tick: model.tick + 1 };
  mark(1);
};
const render = () => {
  const d = dirty;
  dirty = 0;
  if (d & 1) {
    const x = model.tick;
    if (x !== g0) w0.data = g0 = x;
  }
};
go.addEventListener("click", (e) => send(e.isTrusted, Go));
document.body.appendChild(root);
`;
};
