// Sweep 8, live rows: a keyed list of N rows, each holding a controlled
// input and a helper's markup (a component in Solid), and a counter
// elsewhere that `#go` ticks. Nothing a row reads changes, so the cost is
// what a framework spends keeping rows it does not re-render current: in
// beni, restating each live row (backend.md §15.4) — its input compared
// with the value it keeps, its helper's slot visited — and nothing else.

import { beniHeader, scriptRoot, solidHeader, solidMount } from "./common.mjs";

export const beni = (n) => `${beniHeader(`live rows, ${n} rows`)}type alias Row =
    id : Int
    label : String


type alias Model =
    rows : List Row
    tick : Int


type Msg
    = Go
    | Edit Int String


update : Msg, Model → Model
update msg model =
    case msg of
        Go →
            { model | tick = model.tick + 1 }

        Edit id s →
            { model | rows = List.map model.rows λrow → if row.id == id then { row | label = s } else row }


cell : String → Html Msg
cell label = <span class="cell">{label}</span>


view : Model → Html Msg
view model =
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
        <p id="tick">{model.tick}</p>
        <table class="table">
            <tbody>
                <For each={model.rows} keyed={.id}>
                    {λrow →
                        <tr>
                            <td><input value={row.label} onInput={Edit row.id _} /></td>
                            <td>{cell row.label}</td>
                        </tr>
                    }
                </For>
            </tbody>
        </table>
    </div>


main : Browser.Program
main =
    Tea.sandbox
        { init = { rows = List.initialize ${n} λi → { id = i + 1, label = "row \${i + 1}" }, tick = 0 }
        , update = update
        , view = view
        }
`;

export const solid = (v, n) => `${solidHeader(v, `live rows, ${n} rows`, ["createSignal", "For"])}
const Cell = (props) => <span class="cell">{props.label}</span>;

const App = () => {
  const [tick, setTick] = createSignal(0);
  const [rows] = createSignal(
    Array.from({ length: ${n} }, (_, i) => {
      const [label, setLabel] = createSignal(\`row \${i + 1}\`);
      return { id: i + 1, label, setLabel };
    }),
  );
  return (
    <div class="container">
      <button type="button" id="go" onClick={() => setTick((t) => t + 1)}>go</button>
      <p id="tick">{tick()}</p>
      <table class="table">
        <tbody>
          <For each={rows()}>
            {(row) => (
              <tr>
                <td>
                  <input value={row.label()} onInput={(e) => row.setLabel(e.target.value)} />
                </td>
                <td>
                  <Cell label={row.label()} />
                </td>
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  );
};

${solidMount("<App />")}`;

// The plain-script subjects write the page once and tick the counter.
const plain = (n, what) => `// Generated by bench/ui/scaling.mjs: live rows, ${n} rows, ${what}.
${scriptRoot}root.innerHTML = '<button type="button" id="go">go</button><p id="tick">0</p><table class="table"><tbody></tbody></table>';
const tbody = root.querySelector("tbody");
for (let i = 1; i <= ${n}; i++) {
  const tr = document.createElement("tr");
  tr.innerHTML = '<td><input></td><td><span class="cell"></span></td>';
  tr.querySelector("input").value = "row " + i;
  tr.querySelector("span").textContent = "row " + i;
  tbody.appendChild(tr);
}
const tickText = document.getElementById("tick").firstChild;
let tick = 0;
document.getElementById("go").addEventListener("click", () => {
  tick++;
  tickText.data = tick;
});
`;

export const p2 = (n) => plain(n, "P2 (the vanilla page)");
export const vanilla = (n) => plain(n, "vanilla");
