// Sweep 8, live rows: a keyed list of N rows, each holding a controlled
// input and a helper's markup (a component in Solid), and a counter
// elsewhere that `#go` ticks. Nothing a row reads changes, so the cost is
// what a framework spends keeping rows it does not re-render current: in
// beni, restating each live row (backend.md §15.4) — its input compared
// with the value it keeps, its helper's slot visited — and nothing else.

import { beniHeader, p3Loop, p3Root, p3RowTemplate, p3Rows, scriptRoot, solidHeader, solidMount } from "./common.mjs";

export const beni = (n) => `${beniHeader(`live rows, ${n} rows`)}type alias Row =
    id : Int
    label : String


type alias Model =
    rows : List Row
    tick : Int


type Msg
    = Go
    | Edit Int String


update : Msg, Model → Model
update msg model =
    case msg of
        Go →
            { model | tick = model.tick + 1 }

        Edit id s →
            { model | rows = List.map model.rows λrow → if row.id == id then { row | label = s } else row }


cell : String → Html Msg
cell label = <span class="cell">{label}</span>


view : Model → Html Msg
view model =
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
        <p id="tick">{model.tick}</p>
        <table class="table">
            <tbody>
                <For each={model.rows} keyed={.id}>
                    {λrow →
                        <tr>
                            <td><input value={row.label} onInput={Edit row.id _} /></td>
                            <td>{cell row.label}</td>
                        </tr>
                    }
                </For>
            </tbody>
        </table>
    </div>


main : Browser.Program
main =
    Tea.sandbox
        { init = { rows = List.initialize ${n} λi → { id = i + 1, label = "row \${i + 1}" }, tick = 0 }
        , update = update
        , view = view
        }
`;

export const solid = (v, n) => `${solidHeader(v, `live rows, ${n} rows`, ["createSignal", "For"])}
const Cell = (props) => <span class="cell">{props.label}</span>;

const App = () => {
  const [tick, setTick] = createSignal(0);
  const [rows] = createSignal(
    Array.from({ length: ${n} }, (_, i) => {
      const [label, setLabel] = createSignal(\`row \${i + 1}\`);
      return { id: i + 1, label, setLabel };
    }),
  );
  return (
    <div class="container">
      <button type="button" id="go" onClick={() => setTick((t) => t + 1)}>go</button>
      <p id="tick">{tick()}</p>
      <table class="table">
        <tbody>
          <For each={rows()}>
            {(row) => (
              <tr>
                <td>
                  <input value={row.label()} onInput={(e) => row.setLabel(e.target.value)} />
                </td>
                <td>
                  <Cell label={row.label()} />
                </td>
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  );
};

${solidMount("<App />")}`;

// The plain-script subjects write the page once and tick the counter.
const plain = (n, what) => `// Generated by bench/ui/scaling.mjs: live rows, ${n} rows, ${what}.
${scriptRoot}root.innerHTML = '<button type="button" id="go">go</button><p id="tick">0</p><table class="table"><tbody></tbody></table>';
const tbody = root.querySelector("tbody");
for (let i = 1; i <= ${n}; i++) {
  const tr = document.createElement("tr");
  tr.innerHTML = '<td><input></td><td><span class="cell"></span></td>';
  tr.querySelector("input").value = "row " + i;
  tr.querySelector("span").textContent = "row " + i;
  tbody.appendChild(tr);
}
const tickText = document.getElementById("tick").firstChild;
let tick = 0;
document.getElementById("go").addEventListener("click", () => {
  tick++;
  tickText.data = tick;
});
`;

// P3 (research 60): message-indexed rendering, with the controlled inputs
// kept by a dirty set (research 58 §5(c)).
// - W1(Go) = {tick}: one group; no row is visited.
// - W1(Edit) = {rows[*].label}: the `List.map` idiom, which keeps the
//   length, the order and every key (`{ row | label = s }` keeps `id`). Its
//   edit script is a walk by position comparing each element with the item
//   its instance holds (core's `map` returns the same element for a row it
//   did not change, and the same list when it changed none); an instance
//   whose item changed is marked. This walk is O(n), research 58 §5(a)'s
//   cost for the idiom without slice C.
// - A row's one group reads `row.label` and writes the input's value (when
//   the DOM differs, as beni's controlled input does) and the cell's text;
//   `cell` is used once and inlined.
// - The input listener is delegated to the `<tbody>`, the list's parent: it
//   marks the input dirty, then sends `Edit`. After the groups, every dirty
//   input is compared with the model and set back if they differ, then the
//   set is emptied: a render visits the inputs a user touched, and no other.
export const p3 = (n) => `// Generated by bench/ui/scaling.mjs: live rows, ${n} rows, P3 (research 60).
import { List$initialize, List$map, List$base, List$offset } from "./beni-dev/_core/List.mjs";
${p3Loop}${p3Rows}let edited = [];
let model = { rows: List$initialize(${n}, (i) => ({ id: i + 1, label: \`row \${i + 1}\` })), tick: 0 };
${p3Root('<div class=container><button type=button id=go>go</button><p id=tick>0</p><table class=table><tbody></tbody></table></div>')}const go = root.firstChild;
const w0 = go.nextSibling.firstChild;
const tbody = go.nextSibling.nextSibling.firstChild;
let g0 = 0;
${p3RowTemplate("<tr><td><input></td><td><span class=cell> </span></td></tr>")}const make = (x) => {
  const e = rowProto.cloneNode(true);
  const input = e.firstChild.firstChild;
  const cell = e.lastChild.firstChild.firstChild;
  const i = { e, it: x, input, cell, l: x.label, m: false, d: false };
  input.value = x.label;
  cell.data = x.label;
  input.$r = i;
  return i;
};
let insts = [];
{
  const rows = model.rows;
  const b = List$base(rows);
  const o = List$offset(rows);
  const f = document.createDocumentFragment();
  for (let j = 0; j < rows.length; j++) {
    const i = make(b[o + j]);
    insts.push(i);
    f.appendChild(i.e);
  }
  tbody.appendChild(f);
}
const Go = () => {
  model = { ...model, tick: model.tick + 1 };
  mark(1);
};
const Edit = (id, s) => {
  const old = model.rows;
  model = { ...model, rows: List$map(model.rows, (row) => (row.id === id ? { ...row, label: s } : row)) };
  const rows = model.rows;
  if (rows !== old) {
    const b = List$base(rows);
    const o = List$offset(rows);
    for (let j = 0; j < rows.length; j++) {
      const i = insts[j];
      if (b[o + j] !== i.it) {
        i.it = b[o + j];
        markRow(i);
      }
    }
  }
};
// The input event, delegated: the input is dirty from now until the flush.
const input = (i, value) => {
  if (!i.d) {
    i.d = true;
    edited.push(i);
  }
  schedule();
  Edit(i.it.id, value);
};
const render = () => {
  const d = dirty;
  dirty = 0;
  if (d & 1) {
    const x = model.tick;
    if (x !== g0) w0.data = g0 = x;
  }
  const ms = marked;
  marked = [];
  for (const i of ms) {
    i.m = false;
    const x = i.it.label;
    if (x !== i.l) {
      i.l = x;
      if (i.input.value !== x) i.input.value = x;
      i.cell.data = x;
    }
  }
  const es = edited;
  edited = [];
  for (const i of es) {
    i.d = false;
    const x = i.it.label;
    if (i.input.value !== x) i.input.value = x;
  }
};
go.addEventListener("click", (e) => send(e.isTrusted, Go));
tbody.addEventListener("input", (e) => {
  let n = e.target;
  while (n !== tbody && n.$r === undefined) n = n.parentNode;
  if (n !== tbody) send(e.isTrusted, input, n.$r, n.value);
});
document.body.appendChild(root);
`;

export const p2 = (n) => plain(n, "P2 (the vanilla page)");
export const vanilla = (n) => plain(n, "vanilla");
