// Sweep 2, list length: a keyed table of N rows, js-framework-benchmark's
// row markup. `#go` changes the label of one row, the middle one; `#swap`
// exchanges rows 2 and N - 1, as the benchmark's swap exchanges 2 and 999.

import { beniHeader, p2List, p3Loop, p3Root, p3RowTemplate, p3Rows, scriptRoot, solidHeader, solidMount } from "./common.mjs";

export const target = (n) => Math.floor(n / 2);

export const beni = (n) => `${beniHeader(`list length, ${n} rows`)}type alias Row =
    id : Int
    label : String


type alias Model =
    rows : List Row
    version : Int


type Msg
    = Go
    | Swap


update : Msg, Model → Model
update msg model =
    case msg of
        Go →
            version = model.version + 1
            { model
                | version = version
                , rows = List.update model.rows ${target(n)} λrow → { row | label = "changed \${version}" }
            }

        Swap →
            { model | rows = List.swap model.rows 1 ${n - 2} }


view : Model → Html Msg
view model =
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
        <button type="button" id="swap" onClick={Swap}>swap</button>
        <table class="table table-hover table-striped test-data">
            <tbody>
                <For each={model.rows} keyed={.id}>
                    {λrow →
                        <tr>
                            <td class="col-md-1">{row.id}</td>
                            <td class="col-md-4"><a>{row.label}</a></td>
                            <td class="col-md-1" />
                            <td class="col-md-6" />
                        </tr>
                    }
                </For>
            </tbody>
        </table>
    </div>


main : Browser.Program
main =
    Tea.sandbox
        { init = { rows = List.initialize ${n} λi → { id = i + 1, label = "row \${i + 1}" }, version = 0 }
        , update = update
        , view = view
        }
`;

// js-framework-benchmark's Solid idiom: a signal per row for the field that
// changes, the list in a signal, `For` over it.
export const solid = (v, n) => `${solidHeader(v, `list length, ${n} rows`, ["createSignal", "For"])}
const App = () => {
  const [rows, setRows] = createSignal(
    Array.from({ length: ${n} }, (_, i) => {
      const [label, setLabel] = createSignal(\`row \${i + 1}\`);
      return { id: i + 1, label, setLabel };
    }),
  );
  let version = 0;
  const go = () => {
    version++;
    rows()[${target(n)}].setLabel(\`changed \${version}\`);
  };
  const swap = () => {
    const list = rows().slice();
    const t = list[1];
    list[1] = list[${n - 2}];
    list[${n - 2}] = t;
    setRows(list);
  };
  return (
    <div class="container">
      <button type="button" id="go" onClick={go}>go</button>
      <button type="button" id="swap" onClick={swap}>swap</button>
      <table class="table table-hover table-striped test-data">
        <tbody>
          <For each={rows()}>
            {(row) => (
              <tr>
                <td class="col-md-1" textContent={row.id} />
                <td class="col-md-4">
                  <a textContent={row.label()} />
                </td>
                <td class="col-md-1" />
                <td class="col-md-6" />
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  );
};

${solidMount("<App />")}`;

const shell = `<button type="button" id="go">go</button><button type="button" id="swap">swap</button><table class="table table-hover table-striped test-data"><tbody></tbody></table>`;
const rowHtml = '<tr><td class="col-md-1"> </td><td class="col-md-4"><a> </a></td><td class="col-md-1"></td><td class="col-md-6"></td></tr>';

export const p2 = (n) => `// Generated by bench/ui/scaling.mjs: list length, ${n} rows, P2.
${p2List}
${scriptRoot}root.innerHTML = ${JSON.stringify(shell)};
const tbody = root.querySelector("tbody");
const tpl = document.createElement("template");
tpl.innerHTML = ${JSON.stringify(rowHtml)};
const proto = tpl.content.firstChild;
const make = (row) => {
  const el = proto.cloneNode(true);
  const idT = el.firstChild.firstChild;
  const lbT = el.firstChild.nextSibling.firstChild.firstChild;
  idT.data = row.id;
  lbT.data = row.label;
  return { el, item: row, idT, lbT };
};
const patch = (inst, row) => {
  if (inst.item.id !== row.id) inst.idT.data = row.id;
  if (inst.item.label !== row.label) inst.lbT.data = row.label;
};
const list = makeListHole(tbody, make, patch);
let model = { rows: Array.from({ length: ${n} }, (_, i) => ({ id: i + 1, label: \`row \${i + 1}\` })), version: 0 };
const update = (msg, m) => {
  if (msg === "Go") {
    const version = m.version + 1;
    const rows = m.rows.slice();
    rows[${target(n)}] = { ...rows[${target(n)}], label: \`changed \${version}\` };
    return { ...m, version, rows };
  }
  const rows = m.rows.slice();
  const t = rows[1];
  rows[1] = rows[${n - 2}];
  rows[${n - 2}] = t;
  return { ...m, rows };
};
const render = (m) => list(m.rows);
render(model);
for (const msg of ["Go", "Swap"])
  document.getElementById(msg.toLowerCase()).addEventListener("click", () => {
    model = update(msg, model);
    render(model);
  });
`;

// Vanilla, the way js-framework-benchmark's vanillajs keeps its rows: an
// array of rows and an array of their <tr>, written directly.
export const vanilla = (n) => `// Generated by bench/ui/scaling.mjs: list length, ${n} rows, vanilla.
${scriptRoot}root.innerHTML = ${JSON.stringify(shell)};
const tbody = root.querySelector("tbody");
const tpl = document.createElement("template");
tpl.innerHTML = ${JSON.stringify(rowHtml)};
const proto = tpl.content.firstChild;
const data = [];
const trs = [];
for (let i = 0; i < ${n}; i++) {
  const tr = proto.cloneNode(true);
  tr.firstChild.firstChild.data = i + 1;
  tr.firstChild.nextSibling.firstChild.firstChild.data = \`row \${i + 1}\`;
  data.push({ id: i + 1, label: \`row \${i + 1}\` });
  trs.push(tr);
  tbody.appendChild(tr);
}
let version = 0;
document.getElementById("go").addEventListener("click", () => {
  version++;
  data[${target(n)}].label = \`changed \${version}\`;
  trs[${target(n)}].firstChild.nextSibling.firstChild.firstChild.data = data[${target(n)}].label;
});
document.getElementById("swap").addEventListener("click", () => {
  const a = trs[1];
  const b = trs[${n - 2}];
  const afterA = a.nextSibling;
  const afterB = b.nextSibling;
  tbody.insertBefore(b, afterA);
  tbody.insertBefore(a, afterB);
  trs[1] = b;
  trs[${n - 2}] = a;
  const d = data[1];
  data[1] = data[${n - 2}];
  data[${n - 2}] = d;
});
`;

// P3 (research 60): message-indexed rendering. The model half is beni's own
// output: `init` and both branches verbatim, over core's `List` as the
// development build emits it (imported from that build, so the list is
// array-backed and becomes a trie past 256 elements exactly as in beni).
// The view half:
// - W2: `id` is written by no branch, so a row's id is written at mount and
//   has no group. `label` is written by `Go`: one row group.
// - W1(Go) = {version, rows[K].label} with K the literal ${target(n)}: no hole
//   reads `version`; the edit script is "row K's item changed", so the
//   handler points instance K at the new item and marks it. W1(Swap) =
//   {rows ← swap 1 ${n - 2}}: the edit script swaps two instances, in the
//   array and in the DOM; nothing a row shows changed, so no group runs.
// - Each edit applies only when `List.update`/`List.swap` returned a new
//   list (their own guard: an index out of range or equal is a no-op).
// - Instances are kept by position, which only these edit scripts change.
export const p3 = (n) => `// Generated by bench/ui/scaling.mjs: list length, ${n} rows, P3 (research 60).
import { List$initialize, List$swap, List$update, List$unsafeGet, List$base, List$offset } from "./beni-dev/_core/List.mjs";
${p3Loop}${p3Rows}
let model = { rows: List$initialize(${n}, (i) => ({ id: i + 1, label: \`row \${i + 1}\` })), version: 0 };
${p3Root(`<div class=container><button type=button id=go>go</button><button type=button id=swap>swap</button><table class="table table-hover table-striped test-data"><tbody></tbody></table></div>`)}const go = root.firstChild;
const swap = go.nextSibling;
const tbody = swap.nextSibling.firstChild;
${p3RowTemplate("<tr><td class=col-md-1> </td><td class=col-md-4><a> </a></td><td class=col-md-1></td><td class=col-md-6></td></tr>")}const make = (x) => {
  const e = rowProto.cloneNode(true);
  const td = e.firstChild;
  const lb = td.nextSibling.firstChild.firstChild;
  td.firstChild.data = x.id;
  lb.data = x.label;
  return { e, it: x, lb, l: x.label, m: false };
};
let insts = [];
{
  const rows = model.rows;
  const b = List$base(rows);
  const o = List$offset(rows);
  const f = document.createDocumentFragment();
  for (let j = 0; j < rows.length; j++) {
    const i = make(b[o + j]);
    insts.push(i);
    f.appendChild(i.e);
  }
  tbody.appendChild(f);
}
const Go = () => {
  const old = model.rows;
  const version = model.version + 1;
  model = { ...model, version, rows: List$update(model.rows, ${target(n)}, (row) => ({ ...row, label: \`changed \${version}\` })) };
  if (model.rows !== old) {
    const i = insts[${target(n)}];
    i.it = List$unsafeGet(model.rows, ${target(n)});
    markRow(i);
  }
};
const Swap = () => {
  const old = model.rows;
  model = { ...model, rows: List$swap(model.rows, 1, ${n - 2}) };
  if (model.rows !== old) {
    const a = insts[1];
    const b = insts[${n - 2}];
    const after = b.e.nextSibling;
    tbody.insertBefore(b.e, a.e);
    tbody.insertBefore(a.e, after);
    insts[1] = b;
    insts[${n - 2}] = a;
  }
};
const render = () => {
  const ms = marked;
  marked = [];
  for (const i of ms) {
    i.m = false;
    const x = i.it.label;
    if (x !== i.l) i.lb.data = i.l = x;
  }
};
go.addEventListener("click", (e) => send(e.isTrusted, Go));
swap.addEventListener("click", (e) => send(e.isTrusted, Swap));
document.body.appendChild(root);
`;
