// Sweep 9, helper tree: a binary tree of D levels drawn by one recursive
// view helper (a component in Solid), 2^(D+1) - 1 calls, none holding a
// controlled input, and a counter elsewhere that `#go` ticks. Nothing the
// tree reads changes, so the cost is what a framework spends deciding
// that: in beni, whether any skipped call's markup is live (backend.md
// §15.4) — it is not, so nothing under the tree should be visited.

import { beniHeader, scriptRoot, solidHeader, solidMount } from "./common.mjs";

export const nodes = (d) => 2 ** (d + 1) - 1;

export const beni = (d) => `${beniHeader(`helper tree, ${d} levels`)}type alias Model =
    label : String
    tick : Int


type Msg
    = Go


update : Msg, Model → Model
update msg model =
    case msg of
        Go →
            { model | tick = model.tick + 1 }


branch : Int, String → Html Msg
branch depth label =
    if depth == 0 then
        <i>{label}</i>
    else
        <div>{branch (depth - 1) label}{branch (depth - 1) label}</div>


view : Model → Html Msg
view model =
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
        <p id="tick">{model.tick}</p>
        {branch ${d} model.label}
    </div>


main : Browser.Program
main = Tea.sandbox { init = { label = "leaf", tick = 0 }, update = update, view = view }
`;

export const solid = (v, d) => `${solidHeader(v, `helper tree, ${d} levels`, ["createSignal", "Show"])}
const Branch = (props) => (
  <Show when={props.depth > 0} fallback={<i>{props.label}</i>}>
    <div>
      <Branch depth={props.depth - 1} label={props.label} />
      <Branch depth={props.depth - 1} label={props.label} />
    </div>
  </Show>
);

const App = () => {
  const [tick, setTick] = createSignal(0);
  const [label] = createSignal("leaf");
  return (
    <div class="container">
      <button type="button" id="go" onClick={() => setTick((t) => t + 1)}>go</button>
      <p id="tick">{tick()}</p>
      <Branch depth={${d}} label={label()} />
    </div>
  );
};

${solidMount("<App />")}`;

const plain = (d, what) => `// Generated by bench/ui/scaling.mjs: helper tree, ${d} levels, ${what}.
${scriptRoot}const branch = (depth) => (depth === 0 ? "<i>leaf</i>" : "<div>" + branch(depth - 1) + branch(depth - 1) + "</div>");
root.innerHTML = '<button type="button" id="go">go</button><p id="tick">0</p>' + branch(${d});
const tickText = document.getElementById("tick").firstChild;
let tick = 0;
document.getElementById("go").addEventListener("click", () => {
  tick++;
  tickText.data = tick;
});
`;

export const p2 = (d) => plain(d, "P2 (the vanilla page)");
export const vanilla = (d) => plain(d, "vanilla");
