// Sweep 3, model width: a model record of W number fields, each shown in
// its own hole, ten to a `<section>`. `#go` adds one to the middle field.
// Solid keeps a record of state in a store.

import { beniHeader, chunks, indent, range, scriptRoot, solidHeader, solidMount } from "./common.mjs";

export const middle = (w) => Math.floor(w / 2);
const sections = (w, hole) =>
  chunks(range(w), 10)
    .map((ks) => `<section>\n${ks.map((k) => `    ${hole(k)}`).join("\n")}\n</section>`)
    .join("\n");
const beniHole = (w) => (k) => (k === middle(w) ? `<p id="changed">{model.f${k}}</p>` : `<p>{model.f${k}}</p>`);
const solidHole = (w) => (k) => (k === middle(w) ? `<p id="changed">{s.f${k}}</p>` : `<p>{s.f${k}}</p>`);

export const beni = (w) => `${beniHeader(`model width, ${w} fields`)}type alias Model =
${range(w)
  .map((k) => `    f${k} : Int`)
  .join("\n")}


type Msg
    = Go


update : Msg, Model → Model
update msg model =
    case msg of
        Go →
            { model | f${middle(w)} = model.f${middle(w)} + 1 }


view : Model → Html Msg
view model =
    <div class="container">
        <button type="button" id="go" onClick={Go}>go</button>
${indent(sections(w, beniHole(w)), 8)}
    </div>


init : Model
init =
    { f0 = 0
${range(w)
  .slice(1)
  .map((k) => `    , f${k} = ${k}`)
  .join("\n")}
    }


main : Browser.Program
main = Tea.sandbox { init = init, update = update, view = view }
`;

const initObject = (w) => `{ ${range(w)
  .map((k) => `f${k}: ${k}`)
  .join(", ")} }`;

export const solid = (v, w) => `${solidHeader(v, `model width, ${w} fields`, [], ["createStore"])}
const App = () => {
  const [s, setS] = createStore(${initObject(w)});
  const go = () => ${v === 1 ? `setS("f${middle(w)}", (x) => x + 1)` : `setS((d) => {\n    d.f${middle(w)} += 1;\n  })`};
  return (
    <div class="container">
      <button type="button" id="go" onClick={go}>go</button>
${indent(sections(w, solidHole(w)), 6)}
    </div>
  );
};

${solidMount("<App />")}`;

const shellHtml = (w) =>
  `<button type="button" id="go">go</button>${chunks(range(w), 10)
    .map((ks) => `<section>${ks.map((k) => (k === middle(w) ? `<p id="changed"> </p>` : "<p> </p>")).join("")}</section>`)
    .join("")}`;

export const p2 = (w) => `// Generated by bench/ui/scaling.mjs: model width, ${w} fields, P2.
${scriptRoot}root.innerHTML = ${JSON.stringify(shellHtml(w))};
const h = Array.from(root.querySelectorAll("p"), (p) => p.firstChild);
const v = new Array(h.length);
let model = ${initObject(w)};
const update = (msg, m) => (msg === "Go" ? { ...m, f${middle(w)}: m.f${middle(w)} + 1 } : m);
function render(m) {
  let x;
${range(w)
  .map((k) => `  if ((x = m.f${k}) !== v[${k}]) h[${k}].data = v[${k}] = x;`)
  .join("\n")}
}
render(model);
document.getElementById("go").addEventListener("click", () => {
  model = update("Go", model);
  render(model);
});
`;

export const vanilla = (w) => `// Generated by bench/ui/scaling.mjs: model width, ${w} fields, vanilla.
${scriptRoot}root.innerHTML = ${JSON.stringify(shellHtml(w))};
const ps = root.querySelectorAll("p");
const state = ${initObject(w)};
for (let k = 0; k < ${w}; k++) ps[k].firstChild.data = state["f" + k];
const changed = document.getElementById("changed").firstChild;
document.getElementById("go").addEventListener("click", () => {
  state.f${middle(w)} += 1;
  changed.data = state.f${middle(w)};
});
`;
