//! Makes the compiler build id (docs/design/fast-compiler.md §8, *The
//! persistent cache, and its key*, amended 2026-10-03):
//!
//! ```
//! build_id <options out> <hex out> <zig version> <optimize> <triple>
//!          <backend> <build.zig> <src dir> <core dir> [<name> <dir>]...
//! ```
//!
//! Only `build.zig` runs this, once per compiler it builds. It writes the
//! compiler's `build_options` module, whose `build_id` is the id, and the id
//! as 32 lowercase hex digits for the checked core's maker.
//!
//! **A step of the build, not a value of its configuration**, because
//! `zig build --watch` does not configure again after an edit: an id computed
//! while configuring stayed the first build's, and the rebuilt binary claimed
//! to be a compiler that no longer existed. Here every term is a declared
//! input of the step — the strings as arguments, `build.zig` as a file, and
//! each tree as a copy the build system makes and tracks, file set and bytes
//! — so the step runs again whenever one changes, a file added, edited or
//! deleted included, and a binary's id is always the hash of the sources it
//! was built from.
//!
//! The recipe is `SipHash128(1, 3)` — the compiler's one hash function
//! (`src/resolve/iface_bytes.zig`) — over the recipe tag, the Zig version
//! string, the optimize mode, the target triple, `self_hosted` when the
//! backend is the self-hosted one, `build.zig`, every file under `src/`,
//! every file of the core the binary embeds (its `.beni` modules sorted by
//! path, then its other files sorted by path) and every file of every
//! platform it carries, in the order given: each a name, then its bytes, in
//! sorted path order, each field preceded by its length so that two splits
//! of one concatenation cannot agree. A name is relative to its tree, never
//! absolute, so where the project lives on disk is not a term. A file or
//! directory whose name begins with `.` is not part of a tree.
//!
//! **Everything the binary is built from**, because the id is the cache's
//! one term for "this compiler": a term that left out an input the binary
//! carries would let two compilers that behave differently serve each
//! other's entries (`src/build_id.zig` has what the id is for).
//!
//! Lasting coverage: `tests/blackbox/build_id_test.zig` runs two compilers
//! whose ids this program made from two different cores. That it re-runs
//! under `--watch` is a property of the build graph, not of this program,
//! and is checked by hand: start `zig build --watch`, edit a file under
//! `src/` (or add one), and `zig-out/bin/beni version` prints a new id, the
//! one a one-shot build of the edited tree prints; undo the edit and it
//! prints the old one. Not under `-fincremental --watch` yet: Zig 0.17 keeps
//! the compiler process of the first build there and never hands it the new
//! path of this program's output, so the step re-runs and the binary keeps
//! the old id (`fast-compiler.md` §8, the 2026-10-03 note).

const std = @import("std");
const Allocator = std.mem.Allocator;
const Io = std.Io;

const Hasher = std.hash.SipHash128(1, 3);

/// Bumped whenever the recipe changes, so that two compilers which hash the
/// same inputs differently cannot collide on an id. **v2**: the build
/// script, the embedded core and every file of every platform the binary
/// carries joined `src/`.
const recipe: []const u8 = "BENIBUILDID\x00v2";

pub fn main(init: std.process.Init) u8 {
    const io = init.io;
    const arena = init.arena.allocator();
    var stderr_buffer: [1024]u8 = undefined;
    var stderr_writer = std.Io.File.stderr().writer(io, &stderr_buffer);
    const stderr = &stderr_writer.interface;
    defer stderr.flush() catch {};

    const args = init.minimal.args.toSlice(arena) catch return fail(stderr, "out of memory", .{});
    if (args.len < 10 or (args.len - 10) % 2 != 0) return fail(stderr, "usage: build_id <options out> <hex out> " ++
        "<zig version> <optimize> <triple> <backend> <build.zig> <src dir> <core dir> [<name> <dir>]...", .{});

    const id = digest(arena, io, args[3..]) catch |err| switch (err) {
        error.OutOfMemory => return fail(stderr, "out of memory", .{}),
        error.Reported => return 1,
        else => return fail(stderr, "cannot read the compiler's sources: {t}", .{err}),
    };

    const hex = std.fmt.bytesToHex(id, .lower);
    var options: std.ArrayList(u8) = .empty;
    options.print(arena,
        \\//! Generated by `src/build_id_main.zig`: the compiler build id
        \\//! (docs/design/fast-compiler.md §8; `src/build_id.zig`).
        \\
        \\pub const build_id: [16]u8 = .{{
    , .{}) catch return fail(stderr, "out of memory", .{});
    for (id, 0..) |byte, i| options.print(arena, "{s}0x{x:0>2}", .{ if (i == 0) " " else ", ", byte }) catch
        return fail(stderr, "out of memory", .{});
    options.appendSlice(arena, " };\n") catch return fail(stderr, "out of memory", .{});

    const cwd = std.Io.Dir.cwd();
    cwd.writeFile(io, .{ .sub_path = args[1], .data = options.items }) catch |err|
        return fail(stderr, "cannot write '{s}': {t}", .{ args[1], err });
    cwd.writeFile(io, .{ .sub_path = args[2], .data = &hex }) catch |err|
        return fail(stderr, "cannot write '{s}': {t}", .{ args[2], err });
    return 0;
}

/// The id over `terms`: `<zig version> <optimize> <triple> <backend>
/// <build.zig> <src dir> <core dir> [<name> <dir>]...`.
fn digest(arena: Allocator, io: Io, terms: []const [:0]const u8) ![16]u8 {
    var hasher = Hasher.init(&@as([16]u8, @splat(0)));
    feed(&hasher, recipe);
    feed(&hasher, terms[0]);
    feed(&hasher, terms[1]);
    feed(&hasher, terms[2]);
    // Only the self-hosted build adds a term, so every other id is what it
    // was before the term existed.
    if (std.mem.eql(u8, terms[3], "self_hosted")) {
        feed(&hasher, "self_hosted");
    } else if (!std.mem.eql(u8, terms[3], "-")) {
        return error.UnknownBackend;
    }

    // The build script: what it does with the files below — which it
    // embeds, under which names — is as much the compiler as they are.
    feed(&hasher, "build:build.zig");
    try feedBytes(arena, io, &hasher, terms[4]);

    const src = try tree(arena, io, terms[5]);
    if (src.len == 0) return reported("the compiler source tree at {s} is empty", .{terms[5]});
    for (src) |rel| {
        feed(&hasher, rel);
        try feedBytes(arena, io, &hasher, try std.fs.path.join(arena, &.{ terms[5], rel }));
    }

    // The core, exactly as `build.zig`'s `embedCore` embeds it: its modules,
    // then everything else.
    const core = try tree(arena, io, terms[6]);
    var modules: usize = 0;
    for ([_]bool{ true, false }) |module| for (core) |rel| {
        if (std.mem.endsWith(u8, rel, ".beni") != module) continue;
        if (module) modules += 1;
        feed(&hasher, try std.fmt.allocPrint(arena, "core:{s}", .{rel}));
        try feedBytes(arena, io, &hasher, try std.fs.path.join(arena, &.{ terms[6], rel }));
    };
    if (modules == 0) return reported("the core package at {s} is empty", .{terms[6]});

    // Every platform the binary carries, built in or added by `-Dplatform`:
    // its Zig, because a markup lowering is part of the compiler
    // (`boundary.md` §9.6), and every other file, because the binary embeds
    // it.
    var i: usize = 7;
    while (i < terms.len) : (i += 2) {
        const name = terms[i];
        const dir = terms[i + 1];
        for (try tree(arena, io, dir)) |rel| {
            feed(&hasher, try std.fmt.allocPrint(arena, "platform:{s}/{s}", .{ name, rel }));
            try feedBytes(arena, io, &hasher, try std.fs.path.join(arena, &.{ dir, rel }));
        }
    }

    var out: [16]u8 = undefined;
    hasher.final(&out);
    return out;
}

fn reported(comptime format: []const u8, args: anytype) error{Reported} {
    std.debug.print("build_id: " ++ format ++ "\n", args);
    return error.Reported;
}

/// Every file under `root`, recursively, as paths relative to it with `/`
/// separators, sorted bytewise. Names beginning with `.` are skipped, file
/// or directory, and so is anything that is neither.
fn tree(arena: Allocator, io: Io, root: []const u8) ![]const []const u8 {
    var out: std.ArrayList([]const u8) = .empty;
    try collect(arena, io, root, "", &out);
    std.mem.sort([]const u8, out.items, {}, struct {
        fn lessThan(_: void, x: []const u8, y: []const u8) bool {
            return std.mem.lessThan(u8, x, y);
        }
    }.lessThan);
    return out.items;
}

fn collect(arena: Allocator, io: Io, root: []const u8, prefix: []const u8, out: *std.ArrayList([]const u8)) !void {
    const full = if (prefix.len == 0) root else try std.fs.path.join(arena, &.{ root, prefix });
    var handle = try std.Io.Dir.cwd().openDir(io, full, .{ .iterate = true });
    defer handle.close(io);
    var it = handle.iterate();
    while (try it.next(io)) |entry| {
        if (entry.name.len == 0 or entry.name[0] == '.') continue;
        const rel = if (prefix.len == 0) try arena.dupe(u8, entry.name) else try std.fmt.allocPrint(arena, "{s}/{s}", .{ prefix, entry.name });
        switch (entry.kind) {
            .directory => try collect(arena, io, root, rel, out),
            .file => try out.append(arena, rel),
            else => {},
        }
    }
}

/// One file's bytes, as one field.
fn feedBytes(arena: Allocator, io: Io, hasher: *Hasher, path: []const u8) !void {
    const bytes = try std.Io.Dir.cwd().readFileAlloc(io, path, arena, .unlimited);
    defer arena.free(bytes);
    feed(hasher, bytes);
}

/// One length-prefixed field of the digest.
fn feed(hasher: *Hasher, slice: []const u8) void {
    var len: [8]u8 = undefined;
    std.mem.writeInt(u64, &len, slice.len, .little);
    hasher.update(&len);
    hasher.update(slice);
}

fn fail(stderr: *Io.Writer, comptime format: []const u8, args: anytype) u8 {
    stderr.print("build_id: " ++ format ++ "\n", args) catch {};
    return 1;
}
